# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(u"")
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setAutoRepeat(False)
        self.actionPolski = QAction(MainWindow)
        self.actionPolski.setObjectName(u"actionPolski")
        self.actionPolski.setCheckable(True)
        self.actionPolski.setAutoRepeat(False)
        self.actionha0511kr = QAction(MainWindow)
        self.actionha0511kr.setObjectName(u"actionha0511kr")
        self.actionXxRocketshotxX = QAction(MainWindow)
        self.actionXxRocketshotxX.setObjectName(u"actionXxRocketshotxX")
        self.actionSickmind33 = QAction(MainWindow)
        self.actionSickmind33.setObjectName(u"actionSickmind33")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionChangelog = QAction(MainWindow)
        self.actionChangelog.setObjectName(u"actionChangelog")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionDonate = QAction(MainWindow)
        self.actionDonate.setObjectName(u"actionDonate")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 778, 537))
        self.gridLayout_3 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tabWidget = QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QSize(737, 518))
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.ScoreBoard = QWidget()
        self.ScoreBoard.setObjectName(u"ScoreBoard")
        self.ScoreBoard.setStyleSheet(u"#tabWidget {background-color:rgb(24, 247, 247)}\n"
"\n"
"QPushButton { background: red }\n"
"\n"
".QPushButton {background-color:rgb(240, 240, 240)}")
        self.AwayUp2_Button = QPushButton(self.ScoreBoard)
        self.AwayUp2_Button.setObjectName(u"AwayUp2_Button")
        self.AwayUp2_Button.setGeometry(QRect(607, 57, 101, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AwayUp2_Button.sizePolicy().hasHeightForWidth())
        self.AwayUp2_Button.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(11)
        self.AwayUp2_Button.setFont(font1)
        self.AwayName_Input = QLineEdit(self.ScoreBoard)
        self.AwayName_Input.setObjectName(u"AwayName_Input")
        self.AwayName_Input.setGeometry(QRect(494, 22, 215, 32))
        font2 = QFont()
        font2.setPointSize(14)
        self.AwayName_Input.setFont(font2)
        self.AwayName_Input.setMaxLength(30)
        self.AwayDOWN_Button = QPushButton(self.ScoreBoard)
        self.AwayDOWN_Button.setObjectName(u"AwayDOWN_Button")
        self.AwayDOWN_Button.setGeometry(QRect(494, 167, 101, 31))
        sizePolicy.setHeightForWidth(self.AwayDOWN_Button.sizePolicy().hasHeightForWidth())
        self.AwayDOWN_Button.setSizePolicy(sizePolicy)
        self.AwayDOWN_Button.setFont(font)
        self.AwayScore_Label = QLabel(self.ScoreBoard)
        self.AwayScore_Label.setObjectName(u"AwayScore_Label")
        self.AwayScore_Label.setGeometry(QRect(494, 89, 101, 72))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(48)
        self.AwayScore_Label.setFont(font3)
        self.AwayScore_Label.setText(u"0")
        self.AwayScore_Label.setAlignment(Qt.AlignCenter)
        self.AwayUP_Button = QPushButton(self.ScoreBoard)
        self.AwayUP_Button.setObjectName(u"AwayUP_Button")
        self.AwayUP_Button.setGeometry(QRect(494, 57, 101, 31))
        sizePolicy.setHeightForWidth(self.AwayUP_Button.sizePolicy().hasHeightForWidth())
        self.AwayUP_Button.setSizePolicy(sizePolicy)
        self.AwayUP_Button.setFont(font)
        self.HomeUP2_Button = QPushButton(self.ScoreBoard)
        self.HomeUP2_Button.setObjectName(u"HomeUP2_Button")
        self.HomeUP2_Button.setGeometry(QRect(125, 57, 101, 31))
        sizePolicy.setHeightForWidth(self.HomeUP2_Button.sizePolicy().hasHeightForWidth())
        self.HomeUP2_Button.setSizePolicy(sizePolicy)
        self.HomeUP2_Button.setFont(font1)
        self.HomeDOWN_Button = QPushButton(self.ScoreBoard)
        self.HomeDOWN_Button.setObjectName(u"HomeDOWN_Button")
        self.HomeDOWN_Button.setGeometry(QRect(12, 167, 101, 31))
        sizePolicy.setHeightForWidth(self.HomeDOWN_Button.sizePolicy().hasHeightForWidth())
        self.HomeDOWN_Button.setSizePolicy(sizePolicy)
        self.HomeDOWN_Button.setFont(font)
        self.HomeDOWN_Button.setAutoFillBackground(False)
        self.HomeDOWN_Button.setStyleSheet(u".QPushButton {background-color:rgb(247, 247, 247)}")
        self.HomeName_Input = QLineEdit(self.ScoreBoard)
        self.HomeName_Input.setObjectName(u"HomeName_Input")
        self.HomeName_Input.setGeometry(QRect(12, 22, 215, 32))
        self.HomeName_Input.setFont(font2)
        self.HomeName_Input.setMaxLength(30)
        self.HomeUP_Button = QPushButton(self.ScoreBoard)
        self.HomeUP_Button.setObjectName(u"HomeUP_Button")
        self.HomeUP_Button.setGeometry(QRect(12, 57, 101, 31))
        sizePolicy.setHeightForWidth(self.HomeUP_Button.sizePolicy().hasHeightForWidth())
        self.HomeUP_Button.setSizePolicy(sizePolicy)
        self.HomeUP_Button.setFont(font)
        self.HomeScore_Label = QLabel(self.ScoreBoard)
        self.HomeScore_Label.setObjectName(u"HomeScore_Label")
        self.HomeScore_Label.setGeometry(QRect(12, 89, 101, 72))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.HomeScore_Label.sizePolicy().hasHeightForWidth())
        self.HomeScore_Label.setSizePolicy(sizePolicy1)
        self.HomeScore_Label.setFont(font3)
        self.HomeScore_Label.setText(u"0")
        self.HomeScore_Label.setAlignment(Qt.AlignCenter)
        self.PeriodTime_Label = QLabel(self.ScoreBoard)
        self.PeriodTime_Label.setObjectName(u"PeriodTime_Label")
        self.PeriodTime_Label.setGeometry(QRect(267, 97, 67, 26))
        sizePolicy1.setHeightForWidth(self.PeriodTime_Label.sizePolicy().hasHeightForWidth())
        self.PeriodTime_Label.setSizePolicy(sizePolicy1)
        font4 = QFont()
        font4.setFamily(u"Arial")
        font4.setPointSize(9)
        self.PeriodTime_Label.setFont(font4)
        self.PeriodTime_Label.setAlignment(Qt.AlignCenter)
        self.Clock_Label = QLabel(self.ScoreBoard)
        self.Clock_Label.setObjectName(u"Clock_Label")
        self.Clock_Label.setGeometry(QRect(235, 10, 251, 89))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Clock_Label.sizePolicy().hasHeightForWidth())
        self.Clock_Label.setSizePolicy(sizePolicy2)
        self.Clock_Label.setMaximumSize(QSize(16777215, 100))
        font5 = QFont()
        font5.setFamily(u"Arial")
        font5.setPointSize(60)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setWeight(50)
        font5.setStrikeOut(False)
        self.Clock_Label.setFont(font5)
        self.Clock_Label.setText(u"00:00")
        self.Clock_Label.setAlignment(Qt.AlignCenter)
        self.OverTimeClock_Label = QLabel(self.ScoreBoard)
        self.OverTimeClock_Label.setObjectName(u"OverTimeClock_Label")
        self.OverTimeClock_Label.setGeometry(QRect(357, 122, 111, 32))
        sizePolicy1.setHeightForWidth(self.OverTimeClock_Label.sizePolicy().hasHeightForWidth())
        self.OverTimeClock_Label.setSizePolicy(sizePolicy1)
        self.OverTimeClock_Label.setMaximumSize(QSize(16777215, 50))
        font6 = QFont()
        font6.setFamily(u"Arial")
        font6.setPointSize(20)
        font6.setBold(False)
        font6.setWeight(50)
        self.OverTimeClock_Label.setFont(font6)
        self.OverTimeClock_Label.setText(u"00:00")
        self.OverTimeClock_Label.setAlignment(Qt.AlignCenter)
        self.OverTime_Label = QLabel(self.ScoreBoard)
        self.OverTime_Label.setObjectName(u"OverTime_Label")
        self.OverTime_Label.setGeometry(QRect(382, 97, 58, 26))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.OverTime_Label.sizePolicy().hasHeightForWidth())
        self.OverTime_Label.setSizePolicy(sizePolicy3)
        self.OverTime_Label.setMinimumSize(QSize(0, 25))
        self.OverTime_Label.setFont(font4)
        self.OverTime_Label.setAlignment(Qt.AlignCenter)
        self.PeriodClock_Label = QLabel(self.ScoreBoard)
        self.PeriodClock_Label.setObjectName(u"PeriodClock_Label")
        self.PeriodClock_Label.setGeometry(QRect(246, 122, 111, 32))
        sizePolicy1.setHeightForWidth(self.PeriodClock_Label.sizePolicy().hasHeightForWidth())
        self.PeriodClock_Label.setSizePolicy(sizePolicy1)
        self.PeriodClock_Label.setFont(font6)
        self.PeriodClock_Label.setText(u"00:00")
        self.PeriodClock_Label.setAlignment(Qt.AlignCenter)
        self.Seconds_Input = QSpinBox(self.ScoreBoard)
        self.Seconds_Input.setObjectName(u"Seconds_Input")
        self.Seconds_Input.setGeometry(QRect(375, 170, 65, 35))
        sizePolicy.setHeightForWidth(self.Seconds_Input.sizePolicy().hasHeightForWidth())
        self.Seconds_Input.setSizePolicy(sizePolicy)
        font7 = QFont()
        font7.setPointSize(18)
        self.Seconds_Input.setFont(font7)
        self.Seconds_Input.setAlignment(Qt.AlignCenter)
        self.Seconds_Input.setAccelerated(True)
        self.Seconds_Input.setMaximum(59)
        self.PeriodLength_Label = QLabel(self.ScoreBoard)
        self.PeriodLength_Label.setObjectName(u"PeriodLength_Label")
        self.PeriodLength_Label.setGeometry(QRect(173, 271, 101, 20))
        self.PeriodLength_Label.setFont(font4)
        self.PeriodLength_Label.setAlignment(Qt.AlignCenter)
        self.Minutes_Input = QSpinBox(self.ScoreBoard)
        self.Minutes_Input.setObjectName(u"Minutes_Input")
        self.Minutes_Input.setGeometry(QRect(281, 170, 65, 35))
        self.Minutes_Input.setFont(font7)
        self.Minutes_Input.setAlignment(Qt.AlignCenter)
        self.Minutes_Input.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.Minutes_Input.setAccelerated(True)
        self.Minutes_Input.setProperty("showGroupSeparator", False)
        self.Minutes_Input.setMaximum(999)
        self.Minutes_Input.setSingleStep(1)
        self.Minutes_Input.setValue(0)
        self.Minutes_Input.setDisplayIntegerBase(10)
        self.MinutesPeriod_Input = QSpinBox(self.ScoreBoard)
        self.MinutesPeriod_Input.setObjectName(u"MinutesPeriod_Input")
        self.MinutesPeriod_Input.setGeometry(QRect(281, 262, 65, 35))
        self.MinutesPeriod_Input.setFont(font7)
        self.MinutesPeriod_Input.setAlignment(Qt.AlignCenter)
        self.MinutesPeriod_Input.setAccelerated(True)
        self.MinutesPeriod_Input.setMaximum(999)
        self.MinutesPeriod_Input.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.MinutesPeriod_Input.setValue(0)
        self.MinutesPeriod_Input.setDisplayIntegerBase(10)
        self.Clock_Symbole_Label_3 = QLabel(self.ScoreBoard)
        self.Clock_Symbole_Label_3.setObjectName(u"Clock_Symbole_Label_3")
        self.Clock_Symbole_Label_3.setGeometry(QRect(357, 262, 10, 29))
        font8 = QFont()
        font8.setFamily(u"Arial")
        font8.setPointSize(18)
        font8.setBold(True)
        font8.setWeight(75)
        self.Clock_Symbole_Label_3.setFont(font8)
        self.Clock_Symbole_Label_3.setText(u":")
        self.To_Checkbox = QCheckBox(self.ScoreBoard)
        self.To_Checkbox.setObjectName(u"To_Checkbox")
        self.To_Checkbox.setGeometry(QRect(183, 224, 88, 19))
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.To_Checkbox.sizePolicy().hasHeightForWidth())
        self.To_Checkbox.setSizePolicy(sizePolicy4)
        self.To_Checkbox.setFont(font4)
        self.To_Checkbox.setAutoFillBackground(False)
        self.Clock_Symbole_Label_2 = QLabel(self.ScoreBoard)
        self.Clock_Symbole_Label_2.setObjectName(u"Clock_Symbole_Label_2")
        self.Clock_Symbole_Label_2.setGeometry(QRect(357, 215, 10, 29))
        sizePolicy5 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.Clock_Symbole_Label_2.sizePolicy().hasHeightForWidth())
        self.Clock_Symbole_Label_2.setSizePolicy(sizePolicy5)
        self.Clock_Symbole_Label_2.setFont(font8)
        self.Clock_Symbole_Label_2.setText(u":")
        self.Clock_Symbole_Label = QLabel(self.ScoreBoard)
        self.Clock_Symbole_Label.setObjectName(u"Clock_Symbole_Label")
        self.Clock_Symbole_Label.setGeometry(QRect(357, 170, 10, 29))
        self.Clock_Symbole_Label.setFont(font8)
        self.Clock_Symbole_Label.setText(u":")
        self.SecondsTo_Input = QSpinBox(self.ScoreBoard)
        self.SecondsTo_Input.setObjectName(u"SecondsTo_Input")
        self.SecondsTo_Input.setEnabled(False)
        self.SecondsTo_Input.setGeometry(QRect(375, 215, 65, 35))
        sizePolicy.setHeightForWidth(self.SecondsTo_Input.sizePolicy().hasHeightForWidth())
        self.SecondsTo_Input.setSizePolicy(sizePolicy)
        font9 = QFont()
        font9.setPointSize(18)
        font9.setBold(False)
        font9.setItalic(False)
        font9.setWeight(50)
        font9.setKerning(True)
        self.SecondsTo_Input.setFont(font9)
        self.SecondsTo_Input.setAlignment(Qt.AlignCenter)
        self.SecondsTo_Input.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.SecondsTo_Input.setAccelerated(True)
        self.SecondsTo_Input.setProperty("showGroupSeparator", False)
        self.SecondsTo_Input.setMaximum(59)
        self.SecondsPeriod_Input = QSpinBox(self.ScoreBoard)
        self.SecondsPeriod_Input.setObjectName(u"SecondsPeriod_Input")
        self.SecondsPeriod_Input.setGeometry(QRect(375, 262, 65, 35))
        sizePolicy.setHeightForWidth(self.SecondsPeriod_Input.sizePolicy().hasHeightForWidth())
        self.SecondsPeriod_Input.setSizePolicy(sizePolicy)
        self.SecondsPeriod_Input.setFont(font7)
        self.SecondsPeriod_Input.setAlignment(Qt.AlignCenter)
        self.SecondsPeriod_Input.setAccelerated(True)
        self.SecondsPeriod_Input.setMaximum(59)
        self.MinutesTo_Input = QSpinBox(self.ScoreBoard)
        self.MinutesTo_Input.setObjectName(u"MinutesTo_Input")
        self.MinutesTo_Input.setEnabled(False)
        self.MinutesTo_Input.setGeometry(QRect(281, 215, 65, 35))
        sizePolicy6 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.MinutesTo_Input.sizePolicy().hasHeightForWidth())
        self.MinutesTo_Input.setSizePolicy(sizePolicy6)
        self.MinutesTo_Input.setFont(font7)
        self.MinutesTo_Input.setAlignment(Qt.AlignCenter)
        self.MinutesTo_Input.setAccelerated(True)
        self.MinutesTo_Input.setMaximum(999)
        self.TimeSet_Label = QLabel(self.ScoreBoard)
        self.TimeSet_Label.setObjectName(u"TimeSet_Label")
        self.TimeSet_Label.setGeometry(QRect(189, 179, 71, 20))
        self.TimeSet_Label.setFont(font4)
        self.TimeSet_Label.setAlignment(Qt.AlignCenter)
        self.PeriodUP_Button = QPushButton(self.ScoreBoard)
        self.PeriodUP_Button.setObjectName(u"PeriodUP_Button")
        self.PeriodUP_Button.setGeometry(QRect(479, 299, 61, 31))
        self.PeriodDOWN_Button = QPushButton(self.ScoreBoard)
        self.PeriodDOWN_Button.setObjectName(u"PeriodDOWN_Button")
        self.PeriodDOWN_Button.setGeometry(QRect(619, 299, 61, 31))
        self.StopSound_Button = QPushButton(self.ScoreBoard)
        self.StopSound_Button.setObjectName(u"StopSound_Button")
        self.StopSound_Button.setGeometry(QRect(280, 390, 121, 23))
        self.PeriodTxt_Label = QLabel(self.ScoreBoard)
        self.PeriodTxt_Label.setObjectName(u"PeriodTxt_Label")
        self.PeriodTxt_Label.setGeometry(QRect(550, 250, 70, 27))
        font10 = QFont()
        font10.setFamily(u"Arial")
        font10.setPointSize(16)
        self.PeriodTxt_Label.setFont(font10)
        self.Period_Label = QLabel(self.ScoreBoard)
        self.Period_Label.setObjectName(u"Period_Label")
        self.Period_Label.setGeometry(QRect(546, 279, 71, 71))
        font11 = QFont()
        font11.setFamily(u"Arial")
        font11.setPointSize(48)
        font11.setBold(False)
        font11.setItalic(False)
        font11.setUnderline(False)
        font11.setWeight(50)
        font11.setStrikeOut(False)
        font11.setKerning(True)
        self.Period_Label.setFont(font11)
        self.Period_Label.setText(u"1")
        self.Period_Label.setAlignment(Qt.AlignCenter)
        self.HalfTime_Button = QPushButton(self.ScoreBoard)
        self.HalfTime_Button.setObjectName(u"HalfTime_Button")
        self.HalfTime_Button.setGeometry(QRect(430, 430, 90, 50))
        self.HalfTime_Button.setFont(font)
        self.HalfTime_Button.setCheckable(False)
        self.HalfTime_Button.setChecked(False)
        self.ResetTimer_Button = QPushButton(self.ScoreBoard)
        self.ResetTimer_Button.setObjectName(u"ResetTimer_Button")
        self.ResetTimer_Button.setGeometry(QRect(150, 430, 101, 51))
        self.ResetTimer_Button.setFont(font)
        self.Start_Button = QPushButton(self.ScoreBoard)
        self.Start_Button.setObjectName(u"Start_Button")
        self.Start_Button.setGeometry(QRect(280, 420, 121, 71))
        font12 = QFont()
        font12.setFamily(u"Microsoft JhengHei UI")
        font12.setPointSize(20)
        font12.setBold(False)
        font12.setWeight(50)
        self.Start_Button.setFont(font12)
        self.Start_Button.setStyleSheet(u"")
        self.Swap_Button = QPushButton(self.ScoreBoard)
        self.Swap_Button.setObjectName(u"Swap_Button")
        self.Swap_Button.setGeometry(QRect(650, 430, 90, 51))
        self.Swap_Button.setFont(font)
        self.UpdateTeam_Button = QPushButton(self.ScoreBoard)
        self.UpdateTeam_Button.setObjectName(u"UpdateTeam_Button")
        self.UpdateTeam_Button.setGeometry(QRect(10, 430, 121, 50))
        self.UpdateTeam_Button.setFont(font)
        self.UpdateTeam_Button.setStyleSheet(u"alternate-background-color: rgb(85, 170, 127);")
        self.UpdateTeam_Button.setAutoDefault(False)
        self.UpdateTeam_Button.setFlat(False)
        self.ResetScore_Button = QPushButton(self.ScoreBoard)
        self.ResetScore_Button.setObjectName(u"ResetScore_Button")
        self.ResetScore_Button.setGeometry(QRect(540, 430, 90, 51))
        self.ResetScore_Button.setFont(font)
        self.ResetScore_Button.setStyleSheet(u"")
        self.HalfTimeClock_Label = QLabel(self.ScoreBoard)
        self.HalfTimeClock_Label.setObjectName(u"HalfTimeClock_Label")
        self.HalfTimeClock_Label.setGeometry(QRect(417, 390, 121, 32))
        self.HalfTimeClock_Label.setFont(font6)
        self.HalfTimeClock_Label.setText(u"00:00")
        self.HalfTimeClock_Label.setAlignment(Qt.AlignCenter)
        self.HalfTime_Label = QLabel(self.ScoreBoard)
        self.HalfTime_Label.setObjectName(u"HalfTime_Label")
        self.HalfTime_Label.setGeometry(QRect(430, 352, 91, 41))
        self.HalfTime_Label.setFont(font4)
        self.HalfTime_Label.setAlignment(Qt.AlignCenter)
        self.Error_Text = QLabel(self.ScoreBoard)
        self.Error_Text.setObjectName(u"Error_Text")
        self.Error_Text.setEnabled(True)
        self.Error_Text.setGeometry(QRect(20, 290, 241, 111))
        font13 = QFont()
        font13.setPointSize(8)
        font13.setBold(False)
        font13.setWeight(50)
        self.Error_Text.setFont(font13)
        self.Error_Text.setAutoFillBackground(False)
        self.Error_Text.setTextFormat(Qt.AutoText)
        self.Error_Text.setScaledContents(False)
        self.Error_Text.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.Error_Text.setWordWrap(True)
        self.Error_Text.setMargin(0)
        self.Error_Text.setIndent(0)
        self.tabWidget.addTab(self.ScoreBoard, "")
        self.Settings = QWidget()
        self.Settings.setObjectName(u"Settings")
        self.Timer_Settings = QGroupBox(self.Settings)
        self.Timer_Settings.setObjectName(u"Timer_Settings")
        self.Timer_Settings.setGeometry(QRect(30, 10, 151, 130))
        self.Timer_Settings.setFont(font)
        self.Timer_Settings.setFlat(False)
        self.Timer_Settings.setCheckable(False)
        self.StopWatch_Radio = QRadioButton(self.Timer_Settings)
        self.StopWatch_Radio.setObjectName(u"StopWatch_Radio")
        self.StopWatch_Radio.setGeometry(QRect(11, 30, 91, 17))
        self.StopWatch_Radio.setFont(font)
        self.StopWatch_Radio.setChecked(True)
        self.Timer_Radio = QRadioButton(self.Timer_Settings)
        self.Timer_Radio.setObjectName(u"Timer_Radio")
        self.Timer_Radio.setGeometry(QRect(11, 59, 91, 17))
        self.Timer_Radio.setFont(font)
        self.CurrentTime_Radio = QRadioButton(self.Timer_Settings)
        self.CurrentTime_Radio.setObjectName(u"CurrentTime_Radio")
        self.CurrentTime_Radio.setGeometry(QRect(11, 88, 111, 17))
        font14 = QFont()
        font14.setPointSize(9)
        self.CurrentTime_Radio.setFont(font14)
        self.line_2 = QFrame(self.Settings)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(181, 63, 582, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.Settings)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(380, 0, 3, 140))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.Always_on_top_Checkbox = QCheckBox(self.Settings)
        self.Always_on_top_Checkbox.setObjectName(u"Always_on_top_Checkbox")
        self.Always_on_top_Checkbox.setGeometry(QRect(410, 20, 141, 31))
        self.Always_on_top_Checkbox.setFont(font)
        self.line_4 = QFrame(self.Settings)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(580, 0, 3, 70))
        font15 = QFont()
        font15.setPointSize(12)
        self.line_4.setFont(font15)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.OneTenth_Checkbox = QCheckBox(self.Settings)
        self.OneTenth_Checkbox.setObjectName(u"OneTenth_Checkbox")
        self.OneTenth_Checkbox.setGeometry(QRect(590, 20, 161, 31))
        self.OneTenth_Checkbox.setFont(font)
        self.line_6 = QFrame(self.Settings)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(180, 132, 582, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.Speed_CheckBox = QCheckBox(self.Settings)
        self.Speed_CheckBox.setObjectName(u"Speed_CheckBox")
        self.Speed_CheckBox.setGeometry(QRect(403, 90, 91, 31))
        self.Speed_CheckBox.setFont(font)
        self.SpeedHelp_Button = QPushButton(self.Settings)
        self.SpeedHelp_Button.setObjectName(u"SpeedHelp_Button")
        self.SpeedHelp_Button.setGeometry(QRect(620, 90, 75, 31))
        self.SpeedHelp_Button.setFont(font)
        self.Speed_Input = QSpinBox(self.Settings)
        self.Speed_Input.setObjectName(u"Speed_Input")
        self.Speed_Input.setGeometry(QRect(500, 90, 61, 31))
        self.Speed_Input.setFont(font)
        self.Speed_Input.setAlignment(Qt.AlignCenter)
        self.Speed_Input.setAccelerated(True)
        self.Speed_Input.setMinimum(500)
        self.Speed_Input.setMaximum(3000)
        self.Speed_Input.setSingleStep(1)
        self.Speed_Input.setValue(700)
        self.Timer_Presets = QGroupBox(self.Settings)
        self.Timer_Presets.setObjectName(u"Timer_Presets")
        self.Timer_Presets.setGeometry(QRect(30, 170, 701, 130))
        self.Timer_Presets.setFont(font)
        self.TimerPreset_Checkbox = QCheckBox(self.Timer_Presets)
        self.TimerPreset_Checkbox.setObjectName(u"TimerPreset_Checkbox")
        self.TimerPreset_Checkbox.setGeometry(QRect(40, 26, 141, 31))
        self.TimerPreset_Checkbox.setFont(font)
        self.TenM_Radio = QRadioButton(self.Timer_Presets)
        self.TenM_Radio.setObjectName(u"TenM_Radio")
        self.TenM_Radio.setEnabled(False)
        self.TenM_Radio.setGeometry(QRect(100, 70, 82, 17))
        self.TenM_Radio.setFont(font)
        self.TenM_Radio.setChecked(True)
        self.TwentyM_Radio = QRadioButton(self.Timer_Presets)
        self.TwentyM_Radio.setObjectName(u"TwentyM_Radio")
        self.TwentyM_Radio.setEnabled(False)
        self.TwentyM_Radio.setGeometry(QRect(370, 70, 82, 17))
        self.TwentyM_Radio.setFont(font)
        self.TwelveM_Radio = QRadioButton(self.Timer_Presets)
        self.TwelveM_Radio.setObjectName(u"TwelveM_Radio")
        self.TwelveM_Radio.setEnabled(False)
        self.TwelveM_Radio.setGeometry(QRect(190, 70, 82, 17))
        self.TwelveM_Radio.setFont(font)
        self.ThirtyM_Radio = QRadioButton(self.Timer_Presets)
        self.ThirtyM_Radio.setObjectName(u"ThirtyM_Radio")
        self.ThirtyM_Radio.setEnabled(False)
        self.ThirtyM_Radio.setGeometry(QRect(460, 70, 82, 17))
        self.ThirtyM_Radio.setFont(font)
        self.FifteenM_Radio = QRadioButton(self.Timer_Presets)
        self.FifteenM_Radio.setObjectName(u"FifteenM_Radio")
        self.FifteenM_Radio.setEnabled(False)
        self.FifteenM_Radio.setGeometry(QRect(280, 70, 82, 17))
        self.FifteenM_Radio.setFont(font)
        self.FortyFiveM_Radio = QRadioButton(self.Timer_Presets)
        self.FortyFiveM_Radio.setObjectName(u"FortyFiveM_Radio")
        self.FortyFiveM_Radio.setEnabled(False)
        self.FortyFiveM_Radio.setGeometry(QRect(550, 70, 82, 17))
        self.FortyFiveM_Radio.setFont(font)
        self.line_5 = QFrame(self.Settings)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 340, 752, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.Use_Xml_CheckBox = QCheckBox(self.Settings)
        self.Use_Xml_CheckBox.setObjectName(u"Use_Xml_CheckBox")
        self.Use_Xml_CheckBox.setGeometry(QRect(250, 370, 141, 31))
        self.Use_Xml_CheckBox.setFont(font)
        self.MicroSpeed_CheckBox = QCheckBox(self.Settings)
        self.MicroSpeed_CheckBox.setObjectName(u"MicroSpeed_CheckBox")
        self.MicroSpeed_CheckBox.setGeometry(QRect(190, 90, 101, 31))
        self.MicroSpeed_CheckBox.setFont(font)
        self.MicroSpeed_Input = QSpinBox(self.Settings)
        self.MicroSpeed_Input.setObjectName(u"MicroSpeed_Input")
        self.MicroSpeed_Input.setGeometry(QRect(297, 90, 61, 31))
        self.MicroSpeed_Input.setFont(font)
        self.MicroSpeed_Input.setAlignment(Qt.AlignCenter)
        self.MicroSpeed_Input.setAccelerated(True)
        self.MicroSpeed_Input.setMinimum(20)
        self.MicroSpeed_Input.setMaximum(300)
        self.MicroSpeed_Input.setSingleStep(1)
        self.MicroSpeed_Input.setValue(80)
        self.Use_Files_CheckBox = QCheckBox(self.Settings)
        self.Use_Files_CheckBox.setObjectName(u"Use_Files_CheckBox")
        self.Use_Files_CheckBox.setGeometry(QRect(100, 370, 141, 31))
        self.Use_Files_CheckBox.setFont(font)
        self.tabWidget.addTab(self.Settings, "")
        self.line_6.raise_()
        self.Timer_Settings.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.Always_on_top_Checkbox.raise_()
        self.line_4.raise_()
        self.OneTenth_Checkbox.raise_()
        self.Speed_CheckBox.raise_()
        self.SpeedHelp_Button.raise_()
        self.Speed_Input.raise_()
        self.Timer_Presets.raise_()
        self.line_5.raise_()
        self.Use_Xml_CheckBox.raise_()
        self.MicroSpeed_CheckBox.raise_()
        self.MicroSpeed_Input.raise_()
        self.Use_Files_CheckBox.raise_()
        self.Hotkeys = QWidget()
        self.Hotkeys.setObjectName(u"Hotkeys")
        self.Hotkey_Checkbox = QCheckBox(self.Hotkeys)
        self.Hotkey_Checkbox.setObjectName(u"Hotkey_Checkbox")
        self.Hotkey_Checkbox.setGeometry(QRect(30, 10, 411, 41))
        self.Hotkey_Checkbox.setFont(font1)
        self.line = QFrame(self.Hotkeys)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 50, 751, 21))
        sizePolicy4.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy4)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.HomeUpKey_Label = QLabel(self.Hotkeys)
        self.HomeUpKey_Label.setObjectName(u"HomeUpKey_Label")
        self.HomeUpKey_Label.setGeometry(QRect(10, 91, 70, 20))
        self.HomeUpKey_Label.setFont(font)
        self.HomeUp_Key = QLineEdit(self.Hotkeys)
        self.HomeUp_Key.setObjectName(u"HomeUp_Key")
        self.HomeUp_Key.setEnabled(False)
        self.HomeUp_Key.setGeometry(QRect(80, 91, 130, 20))
        self.HomeDwnKey_Label = QLabel(self.Hotkeys)
        self.HomeDwnKey_Label.setObjectName(u"HomeDwnKey_Label")
        self.HomeDwnKey_Label.setGeometry(QRect(10, 150, 70, 20))
        self.HomeDwnKey_Label.setFont(font)
        self.HomeDwn_Key = QLineEdit(self.Hotkeys)
        self.HomeDwn_Key.setObjectName(u"HomeDwn_Key")
        self.HomeDwn_Key.setEnabled(False)
        self.HomeDwn_Key.setGeometry(QRect(80, 150, 130, 20))
        self.AwayUp_Key = QLineEdit(self.Hotkeys)
        self.AwayUp_Key.setObjectName(u"AwayUp_Key")
        self.AwayUp_Key.setEnabled(False)
        self.AwayUp_Key.setGeometry(QRect(80, 270, 130, 20))
        self.HomeUp2Key_Label = QLabel(self.Hotkeys)
        self.HomeUp2Key_Label.setObjectName(u"HomeUp2Key_Label")
        self.HomeUp2Key_Label.setGeometry(QRect(10, 210, 70, 20))
        self.HomeUp2Key_Label.setFont(font)
        self.AwayUpKey_Label = QLabel(self.Hotkeys)
        self.AwayUpKey_Label.setObjectName(u"AwayUpKey_Label")
        self.AwayUpKey_Label.setGeometry(QRect(10, 270, 70, 20))
        self.AwayUpKey_Label.setFont(font)
        self.HomeUp2_Key = QLineEdit(self.Hotkeys)
        self.HomeUp2_Key.setObjectName(u"HomeUp2_Key")
        self.HomeUp2_Key.setEnabled(False)
        self.HomeUp2_Key.setGeometry(QRect(80, 210, 130, 20))
        self.AwayUp2_Key = QLineEdit(self.Hotkeys)
        self.AwayUp2_Key.setObjectName(u"AwayUp2_Key")
        self.AwayUp2_Key.setEnabled(False)
        self.AwayUp2_Key.setGeometry(QRect(80, 390, 130, 20))
        self.AwayDwnKey_Label = QLabel(self.Hotkeys)
        self.AwayDwnKey_Label.setObjectName(u"AwayDwnKey_Label")
        self.AwayDwnKey_Label.setGeometry(QRect(10, 330, 70, 20))
        self.AwayDwnKey_Label.setFont(font)
        self.AwayUp2Key_Label = QLabel(self.Hotkeys)
        self.AwayUp2Key_Label.setObjectName(u"AwayUp2Key_Label")
        self.AwayUp2Key_Label.setGeometry(QRect(10, 390, 70, 20))
        self.AwayUp2Key_Label.setFont(font)
        self.AwayDwn_Key = QLineEdit(self.Hotkeys)
        self.AwayDwn_Key.setObjectName(u"AwayDwn_Key")
        self.AwayDwn_Key.setEnabled(False)
        self.AwayDwn_Key.setGeometry(QRect(80, 330, 130, 20))
        self.PeriodDwn_Key = QLineEdit(self.Hotkeys)
        self.PeriodDwn_Key.setObjectName(u"PeriodDwn_Key")
        self.PeriodDwn_Key.setEnabled(False)
        self.PeriodDwn_Key.setGeometry(QRect(620, 149, 130, 20))
        self.PeriodUpKey_Label = QLabel(self.Hotkeys)
        self.PeriodUpKey_Label.setObjectName(u"PeriodUpKey_Label")
        self.PeriodUpKey_Label.setGeometry(QRect(519, 90, 91, 20))
        self.PeriodUpKey_Label.setFont(font)
        self.PeriodDwnKey_Label = QLabel(self.Hotkeys)
        self.PeriodDwnKey_Label.setObjectName(u"PeriodDwnKey_Label")
        self.PeriodDwnKey_Label.setGeometry(QRect(519, 149, 91, 20))
        self.PeriodDwnKey_Label.setFont(font)
        self.PeriodUp_Key = QLineEdit(self.Hotkeys)
        self.PeriodUp_Key.setObjectName(u"PeriodUp_Key")
        self.PeriodUp_Key.setEnabled(False)
        self.PeriodUp_Key.setGeometry(QRect(620, 90, 130, 20))
        self.SwapTeams_Key = QLineEdit(self.Hotkeys)
        self.SwapTeams_Key.setObjectName(u"SwapTeams_Key")
        self.SwapTeams_Key.setEnabled(False)
        self.SwapTeams_Key.setGeometry(QRect(350, 330, 130, 20))
        self.StopSundKey_Label = QLabel(self.Hotkeys)
        self.StopSundKey_Label.setObjectName(u"StopSundKey_Label")
        self.StopSundKey_Label.setGeometry(QRect(519, 210, 101, 20))
        self.StopSundKey_Label.setFont(font)
        self.SwapTeamsKey_Label = QLabel(self.Hotkeys)
        self.SwapTeamsKey_Label.setObjectName(u"SwapTeamsKey_Label")
        self.SwapTeamsKey_Label.setGeometry(QRect(249, 330, 91, 20))
        self.SwapTeamsKey_Label.setFont(font)
        self.StopSund_Key = QLineEdit(self.Hotkeys)
        self.StopSund_Key.setObjectName(u"StopSund_Key")
        self.StopSund_Key.setEnabled(False)
        self.StopSund_Key.setGeometry(QRect(620, 210, 130, 20))
        self.ResetTimer_Key = QLineEdit(self.Hotkeys)
        self.ResetTimer_Key.setObjectName(u"ResetTimer_Key")
        self.ResetTimer_Key.setEnabled(False)
        self.ResetTimer_Key.setGeometry(QRect(350, 149, 130, 20))
        self.StartStopKey_Label = QLabel(self.Hotkeys)
        self.StartStopKey_Label.setObjectName(u"StartStopKey_Label")
        self.StartStopKey_Label.setGeometry(QRect(249, 90, 91, 20))
        self.StartStopKey_Label.setFont(font)
        self.ResetTimerKey_Label = QLabel(self.Hotkeys)
        self.ResetTimerKey_Label.setObjectName(u"ResetTimerKey_Label")
        self.ResetTimerKey_Label.setGeometry(QRect(249, 149, 91, 20))
        self.ResetTimerKey_Label.setFont(font)
        self.StartStop_Key = QLineEdit(self.Hotkeys)
        self.StartStop_Key.setObjectName(u"StartStop_Key")
        self.StartStop_Key.setEnabled(False)
        self.StartStop_Key.setGeometry(QRect(350, 90, 130, 20))
        self.ResetScore_Key = QLineEdit(self.Hotkeys)
        self.ResetScore_Key.setObjectName(u"ResetScore_Key")
        self.ResetScore_Key.setEnabled(False)
        self.ResetScore_Key.setGeometry(QRect(350, 269, 130, 20))
        self.HalfTimeKey_Label = QLabel(self.Hotkeys)
        self.HalfTimeKey_Label.setObjectName(u"HalfTimeKey_Label")
        self.HalfTimeKey_Label.setGeometry(QRect(249, 210, 91, 20))
        self.HalfTimeKey_Label.setFont(font)
        self.ResetScoreKey_Label = QLabel(self.Hotkeys)
        self.ResetScoreKey_Label.setObjectName(u"ResetScoreKey_Label")
        self.ResetScoreKey_Label.setGeometry(QRect(249, 269, 91, 20))
        self.ResetScoreKey_Label.setFont(font)
        self.HalfTime_Key = QLineEdit(self.Hotkeys)
        self.HalfTime_Key.setObjectName(u"HalfTime_Key")
        self.HalfTime_Key.setEnabled(False)
        self.HalfTime_Key.setGeometry(QRect(350, 210, 130, 20))
        self.line_7 = QFrame(self.Hotkeys)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(230, 60, 20, 351))
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(self.Hotkeys)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(500, 60, 20, 351))
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.ObsConnectKey_Label = QLabel(self.Hotkeys)
        self.ObsConnectKey_Label.setObjectName(u"ObsConnectKey_Label")
        self.ObsConnectKey_Label.setGeometry(QRect(520, 330, 101, 20))
        self.ObsConnectKey_Label.setFont(font)
        self.ObsConnect_Key = QLineEdit(self.Hotkeys)
        self.ObsConnect_Key.setObjectName(u"ObsConnect_Key")
        self.ObsConnect_Key.setEnabled(False)
        self.ObsConnect_Key.setGeometry(QRect(621, 330, 130, 20))
        self.RemoteOnOffKey_Label = QLabel(self.Hotkeys)
        self.RemoteOnOffKey_Label.setObjectName(u"RemoteOnOffKey_Label")
        self.RemoteOnOffKey_Label.setGeometry(QRect(520, 269, 91, 20))
        self.RemoteOnOffKey_Label.setFont(font)
        self.RemoteOnOff_Key = QLineEdit(self.Hotkeys)
        self.RemoteOnOff_Key.setObjectName(u"RemoteOnOff_Key")
        self.RemoteOnOff_Key.setEnabled(False)
        self.RemoteOnOff_Key.setGeometry(QRect(621, 269, 130, 20))
        self.tabWidget.addTab(self.Hotkeys, "")
        self.Sound = QWidget()
        self.Sound.setObjectName(u"Sound")
        self.PlaySound_Checkbox = QCheckBox(self.Sound)
        self.PlaySound_Checkbox.setObjectName(u"PlaySound_Checkbox")
        self.PlaySound_Checkbox.setEnabled(True)
        self.PlaySound_Checkbox.setGeometry(QRect(40, 40, 121, 41))
        self.PlaySound_Checkbox.setFont(font1)
        self.BrowseFile_Input = QLineEdit(self.Sound)
        self.BrowseFile_Input.setObjectName(u"BrowseFile_Input")
        self.BrowseFile_Input.setEnabled(False)
        self.BrowseFile_Input.setGeometry(QRect(20, 99, 221, 25))
        self.TestSound_Button = QPushButton(self.Sound)
        self.TestSound_Button.setObjectName(u"TestSound_Button")
        self.TestSound_Button.setEnabled(False)
        self.TestSound_Button.setGeometry(QRect(380, 100, 101, 25))
        self.BrowseFile_Button = QPushButton(self.Sound)
        self.BrowseFile_Button.setObjectName(u"BrowseFile_Button")
        self.BrowseFile_Button.setEnabled(False)
        self.BrowseFile_Button.setGeometry(QRect(260, 100, 101, 25))
        self.Volume_Slider = QSlider(self.Sound)
        self.Volume_Slider.setObjectName(u"Volume_Slider")
        self.Volume_Slider.setEnabled(False)
        self.Volume_Slider.setGeometry(QRect(130, 170, 471, 31))
        self.Volume_Slider.setFont(font)
        self.Volume_Slider.setStyleSheet(u"QSlider::handle:horizontal:hover {background:darkblue} \n"
"QSlider::handle:horizontal:pressed {background:darkgrey} \n"
"")
        self.Volume_Slider.setMaximum(100)
        self.Volume_Slider.setValue(50)
        self.Volume_Slider.setOrientation(Qt.Horizontal)
        self.Volume_Slider.setInvertedAppearance(False)
        self.Volume_Slider.setTickPosition(QSlider.NoTicks)
        self.Volume_Label = QLabel(self.Sound)
        self.Volume_Label.setObjectName(u"Volume_Label")
        self.Volume_Label.setGeometry(QRect(270, 220, 101, 41))
        self.Volume_Label.setFont(font1)
        self.Volume_Label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.VolumeVal_Label = QLabel(self.Sound)
        self.VolumeVal_Label.setObjectName(u"VolumeVal_Label")
        self.VolumeVal_Label.setGeometry(QRect(380, 220, 31, 41))
        self.VolumeVal_Label.setFont(font1)
        self.tabWidget.addTab(self.Sound, "")
        self.Remote = QWidget()
        self.Remote.setObjectName(u"Remote")
        self.Remote_Button = QPushButton(self.Remote)
        self.Remote_Button.setObjectName(u"Remote_Button")
        self.Remote_Button.setGeometry(QRect(90, 40, 181, 31))
        self.Remote_Button.setFont(font)
        self.Remote_Button.setCheckable(False)
        self.Remote_Button.setChecked(False)
        self.Remote_Button.setFlat(False)
        self.IP_Label = QLabel(self.Remote)
        self.IP_Label.setObjectName(u"IP_Label")
        self.IP_Label.setGeometry(QRect(80, 215, 561, 31))
        self.IP_Label.setFont(font2)
        self.Status_Label = QLabel(self.Remote)
        self.Status_Label.setObjectName(u"Status_Label")
        self.Status_Label.setGeometry(QRect(210, 280, 441, 71))
        self.Status_Label.setFont(font7)
        self.Status_Label.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.VpsInfo_Label = QLabel(self.Remote)
        self.VpsInfo_Label.setObjectName(u"VpsInfo_Label")
        self.VpsInfo_Label.setGeometry(QRect(80, 250, 561, 21))
        self.VpsInfo_Label.setFont(font15)
        self.StatusTxt_Label = QLabel(self.Remote)
        self.StatusTxt_Label.setObjectName(u"StatusTxt_Label")
        self.StatusTxt_Label.setGeometry(QRect(125, 280, 80, 71))
        self.StatusTxt_Label.setFont(font7)
        self.tabWidget.addTab(self.Remote, "")
        self.Obs = QWidget()
        self.Obs.setObjectName(u"Obs")
        self.HostObs_Label = QLabel(self.Obs)
        self.HostObs_Label.setObjectName(u"HostObs_Label")
        self.HostObs_Label.setGeometry(QRect(30, 40, 91, 31))
        self.HostObs_Label.setFont(font1)
        self.PortObs_Label = QLabel(self.Obs)
        self.PortObs_Label.setObjectName(u"PortObs_Label")
        self.PortObs_Label.setGeometry(QRect(30, 80, 91, 31))
        self.PortObs_Label.setFont(font1)
        self.HostObs_Input = QLineEdit(self.Obs)
        self.HostObs_Input.setObjectName(u"HostObs_Input")
        self.HostObs_Input.setGeometry(QRect(120, 40, 113, 31))
        self.HostObs_Input.setFont(font)
        self.PortObs_Input = QLineEdit(self.Obs)
        self.PortObs_Input.setObjectName(u"PortObs_Input")
        self.PortObs_Input.setGeometry(QRect(120, 80, 113, 31))
        self.PortObs_Input.setFont(font)
        self.DefPort_Label = QLabel(self.Obs)
        self.DefPort_Label.setObjectName(u"DefPort_Label")
        self.DefPort_Label.setGeometry(QRect(250, 80, 111, 31))
        self.DefPort_Label.setFont(font)
        self.DefPort_Label.setFrameShape(QFrame.StyledPanel)
        self.DefPort_Label.setFrameShadow(QFrame.Sunken)
        self.DefHost_Label = QLabel(self.Obs)
        self.DefHost_Label.setObjectName(u"DefHost_Label")
        self.DefHost_Label.setGeometry(QRect(250, 40, 131, 31))
        self.DefHost_Label.setFont(font)
        self.DefHost_Label.setFrameShape(QFrame.StyledPanel)
        self.DefHost_Label.setFrameShadow(QFrame.Sunken)
        self.ConnectObs_Button = QPushButton(self.Obs)
        self.ConnectObs_Button.setObjectName(u"ConnectObs_Button")
        self.ConnectObs_Button.setGeometry(QRect(260, 140, 181, 31))
        self.ConnectObs_Button.setFont(font)
        self.InGameScene_Label = QLabel(self.Obs)
        self.InGameScene_Label.setObjectName(u"InGameScene_Label")
        self.InGameScene_Label.setGeometry(QRect(410, 35, 161, 31))
        self.InGameScene_Label.setFont(font1)
        self.HalfTimeScene_Label = QLabel(self.Obs)
        self.HalfTimeScene_Label.setObjectName(u"HalfTimeScene_Label")
        self.HalfTimeScene_Label.setGeometry(QRect(410, 75, 161, 31))
        self.HalfTimeScene_Label.setFont(font1)
        self.InGameScene_comboBox = QComboBox(self.Obs)
        self.InGameScene_comboBox.setObjectName(u"InGameScene_comboBox")
        self.InGameScene_comboBox.setGeometry(QRect(570, 40, 117, 24))
        self.InGameScene_comboBox.setFont(font1)
        self.InGameScene_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.InGameScene_comboBox.setMinimumContentsLength(10)
        self.InGameScene_comboBox.setFrame(True)
        self.HalfTimeScene_comboBox = QComboBox(self.Obs)
        self.HalfTimeScene_comboBox.setObjectName(u"HalfTimeScene_comboBox")
        self.HalfTimeScene_comboBox.setGeometry(QRect(570, 80, 90, 24))
        self.HalfTimeScene_comboBox.setFont(font1)
        self.HalfTimeScene_comboBox.setEditable(False)
        self.HalfTimeScene_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.HalfTimeScene_comboBox.setMinimumContentsLength(7)
        self.ClockSource_comboBox = QComboBox(self.Obs)
        self.ClockSource_comboBox.setObjectName(u"ClockSource_comboBox")
        self.ClockSource_comboBox.setGeometry(QRect(190, 195, 117, 24))
        self.ClockSource_comboBox.setFont(font1)
        self.ClockSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.ClockSource_comboBox.setMinimumContentsLength(10)
        self.ClockSource_comboBox.setFrame(True)
        self.ClockSource_Label = QLabel(self.Obs)
        self.ClockSource_Label.setObjectName(u"ClockSource_Label")
        self.ClockSource_Label.setGeometry(QRect(30, 190, 161, 31))
        self.ClockSource_Label.setFont(font1)
        self.OverTimeClockSource_comboBox = QComboBox(self.Obs)
        self.OverTimeClockSource_comboBox.setObjectName(u"OverTimeClockSource_comboBox")
        self.OverTimeClockSource_comboBox.setGeometry(QRect(190, 235, 117, 24))
        self.OverTimeClockSource_comboBox.setFont(font1)
        self.OverTimeClockSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.OverTimeClockSource_comboBox.setMinimumContentsLength(10)
        self.OverTimeClockSource_comboBox.setFrame(True)
        self.OverTimeClockSource_Label = QLabel(self.Obs)
        self.OverTimeClockSource_Label.setObjectName(u"OverTimeClockSource_Label")
        self.OverTimeClockSource_Label.setGeometry(QRect(30, 230, 161, 31))
        self.OverTimeClockSource_Label.setFont(font1)
        self.HalfTimeClockSource_comboBox = QComboBox(self.Obs)
        self.HalfTimeClockSource_comboBox.setObjectName(u"HalfTimeClockSource_comboBox")
        self.HalfTimeClockSource_comboBox.setGeometry(QRect(190, 275, 117, 24))
        self.HalfTimeClockSource_comboBox.setFont(font1)
        self.HalfTimeClockSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.HalfTimeClockSource_comboBox.setMinimumContentsLength(10)
        self.HalfTimeClockSource_comboBox.setFrame(True)
        self.HalfTimeClockSource_Label = QLabel(self.Obs)
        self.HalfTimeClockSource_Label.setObjectName(u"HalfTimeClockSource_Label")
        self.HalfTimeClockSource_Label.setGeometry(QRect(30, 270, 161, 31))
        self.HalfTimeClockSource_Label.setFont(font1)
        self.HomeSource_comboBox = QComboBox(self.Obs)
        self.HomeSource_comboBox.setObjectName(u"HomeSource_comboBox")
        self.HomeSource_comboBox.setGeometry(QRect(190, 315, 117, 24))
        self.HomeSource_comboBox.setFont(font1)
        self.HomeSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.HomeSource_comboBox.setMinimumContentsLength(10)
        self.HomeSource_comboBox.setFrame(True)
        self.HomeSource_Label = QLabel(self.Obs)
        self.HomeSource_Label.setObjectName(u"HomeSource_Label")
        self.HomeSource_Label.setGeometry(QRect(30, 310, 161, 31))
        self.HomeSource_Label.setFont(font1)
        self.AwaySource_comboBox = QComboBox(self.Obs)
        self.AwaySource_comboBox.setObjectName(u"AwaySource_comboBox")
        self.AwaySource_comboBox.setGeometry(QRect(190, 355, 117, 24))
        self.AwaySource_comboBox.setFont(font1)
        self.AwaySource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.AwaySource_comboBox.setMinimumContentsLength(10)
        self.AwaySource_comboBox.setFrame(True)
        self.AwaySource_Label = QLabel(self.Obs)
        self.AwaySource_Label.setObjectName(u"AwaySource_Label")
        self.AwaySource_Label.setGeometry(QRect(30, 350, 161, 31))
        self.AwaySource_Label.setFont(font1)
        self.PeriodSource_comboBox = QComboBox(self.Obs)
        self.PeriodSource_comboBox.setObjectName(u"PeriodSource_comboBox")
        self.PeriodSource_comboBox.setGeometry(QRect(570, 315, 117, 24))
        self.PeriodSource_comboBox.setFont(font1)
        self.PeriodSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.PeriodSource_comboBox.setMinimumContentsLength(10)
        self.PeriodSource_comboBox.setFrame(True)
        self.HomeGraphicFile_Label = QLabel(self.Obs)
        self.HomeGraphicFile_Label.setObjectName(u"HomeGraphicFile_Label")
        self.HomeGraphicFile_Label.setGeometry(QRect(360, 390, 161, 31))
        self.HomeGraphicFile_Label.setFont(font1)
        self.AwayGraphicFile_Label = QLabel(self.Obs)
        self.AwayGraphicFile_Label.setObjectName(u"AwayGraphicFile_Label")
        self.AwayGraphicFile_Label.setGeometry(QRect(360, 430, 161, 31))
        self.AwayGraphicFile_Label.setFont(font1)
        self.AwayScoreSource_comboBox = QComboBox(self.Obs)
        self.AwayScoreSource_comboBox.setObjectName(u"AwayScoreSource_comboBox")
        self.AwayScoreSource_comboBox.setGeometry(QRect(570, 275, 117, 24))
        self.AwayScoreSource_comboBox.setFont(font1)
        self.AwayScoreSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.AwayScoreSource_comboBox.setMinimumContentsLength(10)
        self.AwayScoreSource_comboBox.setFrame(True)
        self.HomeScoreSource_comboBox = QComboBox(self.Obs)
        self.HomeScoreSource_comboBox.setObjectName(u"HomeScoreSource_comboBox")
        self.HomeScoreSource_comboBox.setGeometry(QRect(570, 235, 117, 24))
        self.HomeScoreSource_comboBox.setFont(font1)
        self.HomeScoreSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.HomeScoreSource_comboBox.setMinimumContentsLength(10)
        self.HomeScoreSource_comboBox.setFrame(True)
        self.PeriodSource_Label = QLabel(self.Obs)
        self.PeriodSource_Label.setObjectName(u"PeriodSource_Label")
        self.PeriodSource_Label.setGeometry(QRect(410, 310, 161, 31))
        self.PeriodSource_Label.setFont(font1)
        self.HomeScoreSource_Label = QLabel(self.Obs)
        self.HomeScoreSource_Label.setObjectName(u"HomeScoreSource_Label")
        self.HomeScoreSource_Label.setGeometry(QRect(410, 230, 161, 31))
        self.HomeScoreSource_Label.setFont(font1)
        self.AwayScoreSource_Label = QLabel(self.Obs)
        self.AwayScoreSource_Label.setObjectName(u"AwayScoreSource_Label")
        self.AwayScoreSource_Label.setGeometry(QRect(410, 270, 161, 31))
        self.AwayScoreSource_Label.setFont(font1)
        self.HomeGraphicFile_Input = QLineEdit(self.Obs)
        self.HomeGraphicFile_Input.setObjectName(u"HomeGraphicFile_Input")
        self.HomeGraphicFile_Input.setGeometry(QRect(570, 390, 117, 31))
        self.HomeGraphicFile_Input.setFont(font)
        self.AwayGraphicFile_Input = QLineEdit(self.Obs)
        self.AwayGraphicFile_Input.setObjectName(u"AwayGraphicFile_Input")
        self.AwayGraphicFile_Input.setGeometry(QRect(570, 430, 117, 31))
        self.AwayGraphicFile_Input.setFont(font)
        self.HomeGraphicFile_toolButton = QToolButton(self.Obs)
        self.HomeGraphicFile_toolButton.setObjectName(u"HomeGraphicFile_toolButton")
        self.HomeGraphicFile_toolButton.setGeometry(QRect(530, 395, 25, 19))
        self.AwayGraphicFile_toolButton = QToolButton(self.Obs)
        self.AwayGraphicFile_toolButton.setObjectName(u"AwayGraphicFile_toolButton")
        self.AwayGraphicFile_toolButton.setGeometry(QRect(530, 435, 25, 19))
        self.ConnectObs_Label = QLabel(self.Obs)
        self.ConnectObs_Label.setObjectName(u"ConnectObs_Label")
        self.ConnectObs_Label.setGeometry(QRect(466, 137, 251, 31))
        self.ConnectObs_Label.setFont(font1)
        self.HomeGraphicSource_comboBox = QComboBox(self.Obs)
        self.HomeGraphicSource_comboBox.setObjectName(u"HomeGraphicSource_comboBox")
        self.HomeGraphicSource_comboBox.setGeometry(QRect(190, 395, 117, 24))
        self.HomeGraphicSource_comboBox.setFont(font1)
        self.HomeGraphicSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.HomeGraphicSource_comboBox.setMinimumContentsLength(10)
        self.HomeGraphicSource_comboBox.setFrame(True)
        self.HomeGraphicSource_Label = QLabel(self.Obs)
        self.HomeGraphicSource_Label.setObjectName(u"HomeGraphicSource_Label")
        self.HomeGraphicSource_Label.setGeometry(QRect(30, 390, 161, 31))
        self.HomeGraphicSource_Label.setFont(font1)
        self.AwayGraphicSource_comboBox = QComboBox(self.Obs)
        self.AwayGraphicSource_comboBox.setObjectName(u"AwayGraphicSource_comboBox")
        self.AwayGraphicSource_comboBox.setGeometry(QRect(190, 435, 117, 24))
        self.AwayGraphicSource_comboBox.setFont(font1)
        self.AwayGraphicSource_comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.AwayGraphicSource_comboBox.setMinimumContentsLength(10)
        self.AwayGraphicSource_comboBox.setFrame(True)
        self.AwayGraphicSource_Label = QLabel(self.Obs)
        self.AwayGraphicSource_Label.setObjectName(u"AwayGraphicSource_Label")
        self.AwayGraphicSource_Label.setGeometry(QRect(30, 430, 161, 31))
        self.AwayGraphicSource_Label.setFont(font1)
        self.PasswordObs_Label = QLabel(self.Obs)
        self.PasswordObs_Label.setObjectName(u"PasswordObs_Label")
        self.PasswordObs_Label.setGeometry(QRect(30, 120, 91, 31))
        self.PasswordObs_Label.setFont(font1)
        self.PasswordObs_Input = QLineEdit(self.Obs)
        self.PasswordObs_Input.setObjectName(u"PasswordObs_Input")
        self.PasswordObs_Input.setGeometry(QRect(120, 120, 113, 31))
        self.PasswordObs_Input.setFont(font)
        self.PasswordObs_Input.setEchoMode(QLineEdit.Password)
        self.SaveObs_Button = QPushButton(self.Obs)
        self.SaveObs_Button.setObjectName(u"SaveObs_Button")
        self.SaveObs_Button.setGeometry(QRect(500, 180, 80, 31))
        self.LoadObs_Button = QPushButton(self.Obs)
        self.LoadObs_Button.setObjectName(u"LoadObs_Button")
        self.LoadObs_Button.setGeometry(QRect(600, 180, 80, 31))
        self.tabWidget.addTab(self.Obs, "")

        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menuLanguage = QMenu(self.menubar)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuContributers = QMenu(self.menubar)
        self.menuContributers.setObjectName(u"menuContributers")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuDonate = QMenu(self.menubar)
        self.menuDonate.setObjectName(u"menuDonate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.scrollArea, self.HomeName_Input)
        QWidget.setTabOrder(self.HomeName_Input, self.AwayName_Input)
        QWidget.setTabOrder(self.AwayName_Input, self.HomeUP_Button)
        QWidget.setTabOrder(self.HomeUP_Button, self.HomeUP2_Button)
        QWidget.setTabOrder(self.HomeUP2_Button, self.HomeDOWN_Button)
        QWidget.setTabOrder(self.HomeDOWN_Button, self.AwayUP_Button)
        QWidget.setTabOrder(self.AwayUP_Button, self.AwayUp2_Button)
        QWidget.setTabOrder(self.AwayUp2_Button, self.AwayDOWN_Button)
        QWidget.setTabOrder(self.AwayDOWN_Button, self.Minutes_Input)
        QWidget.setTabOrder(self.Minutes_Input, self.Seconds_Input)
        QWidget.setTabOrder(self.Seconds_Input, self.To_Checkbox)
        QWidget.setTabOrder(self.To_Checkbox, self.MinutesTo_Input)
        QWidget.setTabOrder(self.MinutesTo_Input, self.SecondsTo_Input)
        QWidget.setTabOrder(self.SecondsTo_Input, self.MinutesPeriod_Input)
        QWidget.setTabOrder(self.MinutesPeriod_Input, self.SecondsPeriod_Input)
        QWidget.setTabOrder(self.SecondsPeriod_Input, self.PeriodUP_Button)
        QWidget.setTabOrder(self.PeriodUP_Button, self.PeriodDOWN_Button)
        QWidget.setTabOrder(self.PeriodDOWN_Button, self.UpdateTeam_Button)
        QWidget.setTabOrder(self.UpdateTeam_Button, self.ResetTimer_Button)
        QWidget.setTabOrder(self.ResetTimer_Button, self.Start_Button)
        QWidget.setTabOrder(self.Start_Button, self.HalfTime_Button)
        QWidget.setTabOrder(self.HalfTime_Button, self.ResetScore_Button)
        QWidget.setTabOrder(self.ResetScore_Button, self.Swap_Button)
        QWidget.setTabOrder(self.Swap_Button, self.StopSound_Button)
        QWidget.setTabOrder(self.StopSound_Button, self.StopWatch_Radio)
        QWidget.setTabOrder(self.StopWatch_Radio, self.Timer_Radio)
        QWidget.setTabOrder(self.Timer_Radio, self.CurrentTime_Radio)
        QWidget.setTabOrder(self.CurrentTime_Radio, self.Always_on_top_Checkbox)
        QWidget.setTabOrder(self.Always_on_top_Checkbox, self.OneTenth_Checkbox)
        QWidget.setTabOrder(self.OneTenth_Checkbox, self.Speed_CheckBox)
        QWidget.setTabOrder(self.Speed_CheckBox, self.Speed_Input)
        QWidget.setTabOrder(self.Speed_Input, self.SpeedHelp_Button)
        QWidget.setTabOrder(self.SpeedHelp_Button, self.TimerPreset_Checkbox)
        QWidget.setTabOrder(self.TimerPreset_Checkbox, self.TenM_Radio)
        QWidget.setTabOrder(self.TenM_Radio, self.TwelveM_Radio)
        QWidget.setTabOrder(self.TwelveM_Radio, self.FifteenM_Radio)
        QWidget.setTabOrder(self.FifteenM_Radio, self.TwentyM_Radio)
        QWidget.setTabOrder(self.TwentyM_Radio, self.ThirtyM_Radio)
        QWidget.setTabOrder(self.ThirtyM_Radio, self.FortyFiveM_Radio)
        QWidget.setTabOrder(self.FortyFiveM_Radio, self.Use_Xml_CheckBox)
        QWidget.setTabOrder(self.Use_Xml_CheckBox, self.Hotkey_Checkbox)
        QWidget.setTabOrder(self.Hotkey_Checkbox, self.HomeUp_Key)
        QWidget.setTabOrder(self.HomeUp_Key, self.HomeDwn_Key)
        QWidget.setTabOrder(self.HomeDwn_Key, self.HomeUp2_Key)
        QWidget.setTabOrder(self.HomeUp2_Key, self.AwayUp_Key)
        QWidget.setTabOrder(self.AwayUp_Key, self.AwayDwn_Key)
        QWidget.setTabOrder(self.AwayDwn_Key, self.AwayUp2_Key)
        QWidget.setTabOrder(self.AwayUp2_Key, self.StartStop_Key)
        QWidget.setTabOrder(self.StartStop_Key, self.ResetTimer_Key)
        QWidget.setTabOrder(self.ResetTimer_Key, self.HalfTime_Key)
        QWidget.setTabOrder(self.HalfTime_Key, self.ResetScore_Key)
        QWidget.setTabOrder(self.ResetScore_Key, self.SwapTeams_Key)
        QWidget.setTabOrder(self.SwapTeams_Key, self.PeriodUp_Key)
        QWidget.setTabOrder(self.PeriodUp_Key, self.PeriodDwn_Key)
        QWidget.setTabOrder(self.PeriodDwn_Key, self.StopSund_Key)
        QWidget.setTabOrder(self.StopSund_Key, self.PlaySound_Checkbox)
        QWidget.setTabOrder(self.PlaySound_Checkbox, self.BrowseFile_Input)
        QWidget.setTabOrder(self.BrowseFile_Input, self.BrowseFile_Button)
        QWidget.setTabOrder(self.BrowseFile_Button, self.TestSound_Button)
        QWidget.setTabOrder(self.TestSound_Button, self.Volume_Slider)
        QWidget.setTabOrder(self.Volume_Slider, self.Remote_Button)
        QWidget.setTabOrder(self.Remote_Button, self.HostObs_Input)
        QWidget.setTabOrder(self.HostObs_Input, self.PortObs_Input)
        QWidget.setTabOrder(self.PortObs_Input, self.ConnectObs_Button)
        QWidget.setTabOrder(self.ConnectObs_Button, self.InGameScene_comboBox)
        QWidget.setTabOrder(self.InGameScene_comboBox, self.HalfTimeScene_comboBox)

        self.menubar.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuContributers.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDonate.menuAction())
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionPolski)
        self.menuContributers.addAction(self.actionha0511kr)
        self.menuContributers.addAction(self.actionXxRocketshotxX)
        self.menuContributers.addAction(self.actionSickmind33)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionChangelog)
        self.menuHelp.addAction(self.actionHelp)
        self.menuDonate.addAction(self.actionDonate)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(5)
        self.UpdateTeam_Button.setDefault(False)
        self.Remote_Button.setDefault(False)
        self.InGameScene_comboBox.setCurrentIndex(-1)
        self.HalfTimeScene_comboBox.setCurrentIndex(-1)
        self.ClockSource_comboBox.setCurrentIndex(-1)
        self.OverTimeClockSource_comboBox.setCurrentIndex(-1)
        self.HalfTimeClockSource_comboBox.setCurrentIndex(-1)
        self.HomeSource_comboBox.setCurrentIndex(-1)
        self.AwaySource_comboBox.setCurrentIndex(-1)
        self.PeriodSource_comboBox.setCurrentIndex(-1)
        self.AwayScoreSource_comboBox.setCurrentIndex(-1)
        self.HomeScoreSource_comboBox.setCurrentIndex(-1)
        self.HomeGraphicSource_comboBox.setCurrentIndex(-1)
        self.AwayGraphicSource_comboBox.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionPolski.setText(QCoreApplication.translate("MainWindow", u"Polski", None))
        self.actionha0511kr.setText(QCoreApplication.translate("MainWindow", u"ha0511kr", None))
        self.actionXxRocketshotxX.setText(QCoreApplication.translate("MainWindow", u"XxRocketshotxX", None))
        self.actionSickmind33.setText(QCoreApplication.translate("MainWindow", u"Sickmind33", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionChangelog.setText(QCoreApplication.translate("MainWindow", u"Changelog", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.actionDonate.setText(QCoreApplication.translate("MainWindow", u"Donate", None))
        self.AwayUp2_Button.setText(QCoreApplication.translate("MainWindow", u"+2", None))
        self.AwayName_Input.setText("")
        self.AwayName_Input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Away", None))
        self.AwayDOWN_Button.setText(QCoreApplication.translate("MainWindow", u"DOWN", None))
        self.AwayUP_Button.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.HomeUP2_Button.setText(QCoreApplication.translate("MainWindow", u"+2", None))
        self.HomeDOWN_Button.setText(QCoreApplication.translate("MainWindow", u"DOWN", None))
        self.HomeName_Input.setText("")
        self.HomeName_Input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.HomeUP_Button.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.PeriodTime_Label.setText(QCoreApplication.translate("MainWindow", u"Period Time", None))
        self.OverTime_Label.setText(QCoreApplication.translate("MainWindow", u"Over Time", None))
        self.PeriodLength_Label.setText(QCoreApplication.translate("MainWindow", u"Period Length", None))
        self.To_Checkbox.setText(QCoreApplication.translate("MainWindow", u"To(optional)", None))
        self.TimeSet_Label.setText(QCoreApplication.translate("MainWindow", u"Time Set", None))
        self.PeriodUP_Button.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.PeriodDOWN_Button.setText(QCoreApplication.translate("MainWindow", u"DOWN", None))
        self.StopSound_Button.setText(QCoreApplication.translate("MainWindow", u"Stop Sound", None))
        self.PeriodTxt_Label.setText(QCoreApplication.translate("MainWindow", u"Period:", None))
        self.HalfTime_Button.setText(QCoreApplication.translate("MainWindow", u"HalfTime", None))
        self.ResetTimer_Button.setText(QCoreApplication.translate("MainWindow", u"Reset Timer", None))
        self.Start_Button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Swap_Button.setText(QCoreApplication.translate("MainWindow", u"Swap", None))
        self.UpdateTeam_Button.setText(QCoreApplication.translate("MainWindow", u"Update Team", None))
        self.ResetScore_Button.setText(QCoreApplication.translate("MainWindow", u"Reset Score", None))
        self.HalfTime_Label.setText(QCoreApplication.translate("MainWindow", u" Half Time\n"
"Break Time", None))
        self.Error_Text.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Error Output:</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ScoreBoard), QCoreApplication.translate("MainWindow", u"Scoreboard", None))
        self.Timer_Settings.setTitle(QCoreApplication.translate("MainWindow", u"Timer Settings", None))
        self.StopWatch_Radio.setText(QCoreApplication.translate("MainWindow", u"StopWatch", None))
        self.Timer_Radio.setText(QCoreApplication.translate("MainWindow", u"Timer", None))
        self.CurrentTime_Radio.setText(QCoreApplication.translate("MainWindow", u"Current Time", None))
        self.Always_on_top_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Always on top", None))
        self.OneTenth_Checkbox.setText(QCoreApplication.translate("MainWindow", u"1/10 Second min < 1", None))
        self.Speed_CheckBox.setText(QCoreApplication.translate("MainWindow", u"Speed:", None))
        self.SpeedHelp_Button.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.Timer_Presets.setTitle(QCoreApplication.translate("MainWindow", u"Timer Presets", None))
        self.TimerPreset_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Preset Timer Reset", None))
        self.TenM_Radio.setText(QCoreApplication.translate("MainWindow", u"10:00", None))
        self.TwentyM_Radio.setText(QCoreApplication.translate("MainWindow", u"20:00", None))
        self.TwelveM_Radio.setText(QCoreApplication.translate("MainWindow", u"12:00", None))
        self.ThirtyM_Radio.setText(QCoreApplication.translate("MainWindow", u"30:00", None))
        self.FifteenM_Radio.setText(QCoreApplication.translate("MainWindow", u"15:00", None))
        self.FortyFiveM_Radio.setText(QCoreApplication.translate("MainWindow", u"45:00", None))
        self.Use_Xml_CheckBox.setText(QCoreApplication.translate("MainWindow", u"Use XML Flie", None))
        self.MicroSpeed_CheckBox.setText(QCoreApplication.translate("MainWindow", u"1/10 Speed:", None))
        self.Use_Files_CheckBox.setText(QCoreApplication.translate("MainWindow", u"Use Flies", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.Hotkey_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Use Hotkey", None))
        self.HomeUpKey_Label.setText(QCoreApplication.translate("MainWindow", u"Home UP", None))
        self.HomeDwnKey_Label.setText(QCoreApplication.translate("MainWindow", u"Home DWN", None))
        self.HomeUp2Key_Label.setText(QCoreApplication.translate("MainWindow", u"Home +2", None))
        self.AwayUpKey_Label.setText(QCoreApplication.translate("MainWindow", u"Away UP", None))
        self.AwayDwnKey_Label.setText(QCoreApplication.translate("MainWindow", u"Away DWN", None))
        self.AwayUp2Key_Label.setText(QCoreApplication.translate("MainWindow", u"Away +2", None))
        self.PeriodUpKey_Label.setText(QCoreApplication.translate("MainWindow", u"Period UP", None))
        self.PeriodDwnKey_Label.setText(QCoreApplication.translate("MainWindow", u"Period DWN", None))
        self.StopSundKey_Label.setText(QCoreApplication.translate("MainWindow", u"Stop Sound", None))
        self.SwapTeamsKey_Label.setText(QCoreApplication.translate("MainWindow", u"Swap Teams", None))
        self.StartStopKey_Label.setText(QCoreApplication.translate("MainWindow", u"Start/Stop", None))
        self.ResetTimerKey_Label.setText(QCoreApplication.translate("MainWindow", u"Reset Timer", None))
        self.HalfTimeKey_Label.setText(QCoreApplication.translate("MainWindow", u"Half Time", None))
        self.ResetScoreKey_Label.setText(QCoreApplication.translate("MainWindow", u"Reset Score", None))
        self.ObsConnectKey_Label.setText(QCoreApplication.translate("MainWindow", u"Obs Conn/Discon", None))
        self.RemoteOnOffKey_Label.setText(QCoreApplication.translate("MainWindow", u"Remote On/Off", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Hotkeys), QCoreApplication.translate("MainWindow", u"HotKeys", None))
        self.PlaySound_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Play Sound", None))
        self.TestSound_Button.setText(QCoreApplication.translate("MainWindow", u"Test Sound", None))
        self.BrowseFile_Button.setText(QCoreApplication.translate("MainWindow", u"Browse File", None))
        self.Volume_Label.setText(QCoreApplication.translate("MainWindow", u"Volume :", None))
        self.VolumeVal_Label.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sound), QCoreApplication.translate("MainWindow", u"Sound", None))
        self.Remote_Button.setText(QCoreApplication.translate("MainWindow", u"Start Server", None))
        self.IP_Label.setText(QCoreApplication.translate("MainWindow", u"Default IP: 127.0.0.1/Localhost | Port: 1234", None))
        self.Status_Label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.VpsInfo_Label.setText(QCoreApplication.translate("MainWindow", u"If you want to remote over internet please portfoward or use VPS", None))
        self.StatusTxt_Label.setText(QCoreApplication.translate("MainWindow", u"Status: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Remote), QCoreApplication.translate("MainWindow", u"Remote", None))
        self.HostObs_Label.setText(QCoreApplication.translate("MainWindow", u"Host / IP", None))
        self.PortObs_Label.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.DefPort_Label.setText(QCoreApplication.translate("MainWindow", u"default: 4444", None))
        self.DefHost_Label.setText(QCoreApplication.translate("MainWindow", u"default: localhost", None))
        self.ConnectObs_Button.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.InGameScene_Label.setText(QCoreApplication.translate("MainWindow", u"In Game Scene", None))
        self.HalfTimeScene_Label.setText(QCoreApplication.translate("MainWindow", u"Half Time Scene", None))
        self.HalfTimeScene_comboBox.setCurrentText("")
        self.ClockSource_Label.setText(QCoreApplication.translate("MainWindow", u"Clock Source", None))
        self.OverTimeClockSource_Label.setText(QCoreApplication.translate("MainWindow", u"OverTime Clock Source", None))
        self.HalfTimeClockSource_Label.setText(QCoreApplication.translate("MainWindow", u"Half Time Clock Source", None))
        self.HomeSource_Label.setText(QCoreApplication.translate("MainWindow", u"Home Source", None))
        self.AwaySource_Label.setText(QCoreApplication.translate("MainWindow", u"Away Source", None))
        self.HomeGraphicFile_Label.setText(QCoreApplication.translate("MainWindow", u"Home Graphic File", None))
        self.AwayGraphicFile_Label.setText(QCoreApplication.translate("MainWindow", u"Away Graphic File", None))
        self.PeriodSource_Label.setText(QCoreApplication.translate("MainWindow", u"Period Source", None))
        self.HomeScoreSource_Label.setText(QCoreApplication.translate("MainWindow", u"Home Score Source", None))
        self.AwayScoreSource_Label.setText(QCoreApplication.translate("MainWindow", u"Away Score Source", None))
        self.HomeGraphicFile_toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.AwayGraphicFile_toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ConnectObs_Label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.HomeGraphicSource_Label.setText(QCoreApplication.translate("MainWindow", u"Home Graphic Source", None))
        self.AwayGraphicSource_Label.setText(QCoreApplication.translate("MainWindow", u"Away Graphic Source", None))
        self.PasswordObs_Label.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.PasswordObs_Input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"None", None))
        self.SaveObs_Button.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.LoadObs_Button.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Obs), QCoreApplication.translate("MainWindow", u"OBS", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
        self.menuContributers.setTitle(QCoreApplication.translate("MainWindow", u"Contributers", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuDonate.setTitle(QCoreApplication.translate("MainWindow", u"Donate", None))
    # retranslateUi

