# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setAutoRepeat(False)
        self.actionPolski = QAction(MainWindow)
        self.actionPolski.setObjectName(u"actionPolski")
        self.actionPolski.setCheckable(True)
        self.actionPolski.setAutoRepeat(False)
        self.actionha0511kr = QAction(MainWindow)
        self.actionha0511kr.setObjectName(u"actionha0511kr")
        self.actionXxRocketshotxX = QAction(MainWindow)
        self.actionXxRocketshotxX.setObjectName(u"actionXxRocketshotxX")
        self.actionSickmind33 = QAction(MainWindow)
        self.actionSickmind33.setObjectName(u"actionSickmind33")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionChangelog = QAction(MainWindow)
        self.actionChangelog.setObjectName(u"actionChangelog")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionDonate = QAction(MainWindow)
        self.actionDonate.setObjectName(u"actionDonate")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 778, 537))
        self.gridLayout_3 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tabWidget = QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QSize(737, 518))
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"background-color:rgb(200, 200, 200) ;")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.ScoreBoard = QWidget()
        self.ScoreBoard.setObjectName(u"ScoreBoard")
        self.AwayUp2_Button = QPushButton(self.ScoreBoard)
        self.AwayUp2_Button.setObjectName(u"AwayUp2_Button")
        self.AwayUp2_Button.setGeometry(QRect(607, 57, 101, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AwayUp2_Button.sizePolicy().hasHeightForWidth())
        self.AwayUp2_Button.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(11)
        self.AwayUp2_Button.setFont(font1)
        self.AwayName_Input = QLineEdit(self.ScoreBoard)
        self.AwayName_Input.setObjectName(u"AwayName_Input")
        self.AwayName_Input.setGeometry(QRect(494, 22, 215, 32))
        font2 = QFont()
        font2.setPointSize(14)
        self.AwayName_Input.setFont(font2)
        self.AwayName_Input.setMaxLength(30)
        self.AwayDOWN_Button = QPushButton(self.ScoreBoard)
        self.AwayDOWN_Button.setObjectName(u"AwayDOWN_Button")
        self.AwayDOWN_Button.setGeometry(QRect(494, 167, 101, 31))
        sizePolicy.setHeightForWidth(self.AwayDOWN_Button.sizePolicy().hasHeightForWidth())
        self.AwayDOWN_Button.setSizePolicy(sizePolicy)
        self.AwayScore_Label = QLabel(self.ScoreBoard)
        self.AwayScore_Label.setObjectName(u"AwayScore_Label")
        self.AwayScore_Label.setGeometry(QRect(494, 89, 101, 72))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(48)
        self.AwayScore_Label.setFont(font3)
        self.AwayScore_Label.setAlignment(Qt.AlignCenter)
        self.AwayUP_Button = QPushButton(self.ScoreBoard)
        self.AwayUP_Button.setObjectName(u"AwayUP_Button")
        self.AwayUP_Button.setGeometry(QRect(494, 57, 101, 31))
        sizePolicy.setHeightForWidth(self.AwayUP_Button.sizePolicy().hasHeightForWidth())
        self.AwayUP_Button.setSizePolicy(sizePolicy)
        self.HomeUP2_Button = QPushButton(self.ScoreBoard)
        self.HomeUP2_Button.setObjectName(u"HomeUP2_Button")
        self.HomeUP2_Button.setGeometry(QRect(125, 57, 101, 31))
        sizePolicy.setHeightForWidth(self.HomeUP2_Button.sizePolicy().hasHeightForWidth())
        self.HomeUP2_Button.setSizePolicy(sizePolicy)
        self.HomeUP2_Button.setFont(font1)
        self.HomeDOWN_Button = QPushButton(self.ScoreBoard)
        self.HomeDOWN_Button.setObjectName(u"HomeDOWN_Button")
        self.HomeDOWN_Button.setGeometry(QRect(12, 167, 101, 31))
        sizePolicy.setHeightForWidth(self.HomeDOWN_Button.sizePolicy().hasHeightForWidth())
        self.HomeDOWN_Button.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(200, 200, 200, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.HomeDOWN_Button.setPalette(palette)
        self.HomeName_Input = QLineEdit(self.ScoreBoard)
        self.HomeName_Input.setObjectName(u"HomeName_Input")
        self.HomeName_Input.setGeometry(QRect(12, 22, 215, 32))
        self.HomeName_Input.setFont(font2)
        self.HomeName_Input.setMaxLength(30)
        self.HomeUP_Button = QPushButton(self.ScoreBoard)
        self.HomeUP_Button.setObjectName(u"HomeUP_Button")
        self.HomeUP_Button.setGeometry(QRect(12, 57, 101, 31))
        sizePolicy.setHeightForWidth(self.HomeUP_Button.sizePolicy().hasHeightForWidth())
        self.HomeUP_Button.setSizePolicy(sizePolicy)
        self.HomeScore_Label = QLabel(self.ScoreBoard)
        self.HomeScore_Label.setObjectName(u"HomeScore_Label")
        self.HomeScore_Label.setGeometry(QRect(12, 89, 101, 72))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.HomeScore_Label.sizePolicy().hasHeightForWidth())
        self.HomeScore_Label.setSizePolicy(sizePolicy1)
        self.HomeScore_Label.setFont(font3)
        self.HomeScore_Label.setAlignment(Qt.AlignCenter)
        self.PeriodTime_Label = QLabel(self.ScoreBoard)
        self.PeriodTime_Label.setObjectName(u"PeriodTime_Label")
        self.PeriodTime_Label.setGeometry(QRect(267, 97, 67, 26))
        sizePolicy1.setHeightForWidth(self.PeriodTime_Label.sizePolicy().hasHeightForWidth())
        self.PeriodTime_Label.setSizePolicy(sizePolicy1)
        font4 = QFont()
        font4.setFamily(u"Arial")
        font4.setPointSize(9)
        self.PeriodTime_Label.setFont(font4)
        self.PeriodTime_Label.setAlignment(Qt.AlignCenter)
        self.Clock_Label = QLabel(self.ScoreBoard)
        self.Clock_Label.setObjectName(u"Clock_Label")
        self.Clock_Label.setGeometry(QRect(258, 10, 198, 89))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Clock_Label.sizePolicy().hasHeightForWidth())
        self.Clock_Label.setSizePolicy(sizePolicy2)
        self.Clock_Label.setMaximumSize(QSize(16777215, 100))
        font5 = QFont()
        font5.setFamily(u"Arial")
        font5.setPointSize(60)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setWeight(50)
        font5.setStrikeOut(False)
        self.Clock_Label.setFont(font5)
        self.Clock_Label.setAlignment(Qt.AlignCenter)
        self.ExtraClock_Label = QLabel(self.ScoreBoard)
        self.ExtraClock_Label.setObjectName(u"ExtraClock_Label")
        self.ExtraClock_Label.setGeometry(QRect(380, 122, 68, 32))
        sizePolicy1.setHeightForWidth(self.ExtraClock_Label.sizePolicy().hasHeightForWidth())
        self.ExtraClock_Label.setSizePolicy(sizePolicy1)
        self.ExtraClock_Label.setMaximumSize(QSize(16777215, 50))
        font6 = QFont()
        font6.setFamily(u"Arial")
        font6.setPointSize(20)
        font6.setBold(False)
        font6.setWeight(50)
        self.ExtraClock_Label.setFont(font6)
        self.ExtraClock_Label.setAlignment(Qt.AlignCenter)
        self.ExtraTime_Label = QLabel(self.ScoreBoard)
        self.ExtraTime_Label.setObjectName(u"ExtraTime_Label")
        self.ExtraTime_Label.setGeometry(QRect(382, 97, 58, 26))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.ExtraTime_Label.sizePolicy().hasHeightForWidth())
        self.ExtraTime_Label.setSizePolicy(sizePolicy3)
        self.ExtraTime_Label.setMinimumSize(QSize(0, 25))
        self.ExtraTime_Label.setFont(font4)
        self.ExtraTime_Label.setAlignment(Qt.AlignCenter)
        self.PeriodClock_Label = QLabel(self.ScoreBoard)
        self.PeriodClock_Label.setObjectName(u"PeriodClock_Label")
        self.PeriodClock_Label.setGeometry(QRect(266, 122, 68, 32))
        sizePolicy1.setHeightForWidth(self.PeriodClock_Label.sizePolicy().hasHeightForWidth())
        self.PeriodClock_Label.setSizePolicy(sizePolicy1)
        self.PeriodClock_Label.setFont(font6)
        self.PeriodClock_Label.setAlignment(Qt.AlignCenter)
        self.Seconds_Input = QSpinBox(self.ScoreBoard)
        self.Seconds_Input.setObjectName(u"Seconds_Input")
        self.Seconds_Input.setGeometry(QRect(375, 170, 65, 35))
        sizePolicy.setHeightForWidth(self.Seconds_Input.sizePolicy().hasHeightForWidth())
        self.Seconds_Input.setSizePolicy(sizePolicy)
        font7 = QFont()
        font7.setPointSize(18)
        self.Seconds_Input.setFont(font7)
        self.Seconds_Input.setAlignment(Qt.AlignCenter)
        self.Seconds_Input.setAccelerated(True)
        self.Seconds_Input.setMaximum(59)
        self.PeriodLength_Label = QLabel(self.ScoreBoard)
        self.PeriodLength_Label.setObjectName(u"PeriodLength_Label")
        self.PeriodLength_Label.setGeometry(QRect(173, 271, 101, 20))
        self.PeriodLength_Label.setFont(font4)
        self.PeriodLength_Label.setAlignment(Qt.AlignCenter)
        self.Minutes_Input = QSpinBox(self.ScoreBoard)
        self.Minutes_Input.setObjectName(u"Minutes_Input")
        self.Minutes_Input.setGeometry(QRect(281, 170, 65, 35))
        self.Minutes_Input.setFont(font7)
        self.Minutes_Input.setAlignment(Qt.AlignCenter)
        self.Minutes_Input.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.Minutes_Input.setAccelerated(True)
        self.Minutes_Input.setProperty("showGroupSeparator", False)
        self.Minutes_Input.setMaximum(999)
        self.Minutes_Input.setSingleStep(1)
        self.Minutes_Input.setValue(0)
        self.Minutes_Input.setDisplayIntegerBase(10)
        self.MinutesPeriod_Input = QSpinBox(self.ScoreBoard)
        self.MinutesPeriod_Input.setObjectName(u"MinutesPeriod_Input")
        self.MinutesPeriod_Input.setGeometry(QRect(281, 262, 65, 35))
        self.MinutesPeriod_Input.setFont(font7)
        self.MinutesPeriod_Input.setAlignment(Qt.AlignCenter)
        self.MinutesPeriod_Input.setAccelerated(True)
        self.MinutesPeriod_Input.setMaximum(999)
        self.MinutesPeriod_Input.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.MinutesPeriod_Input.setValue(0)
        self.MinutesPeriod_Input.setDisplayIntegerBase(10)
        self.Clock_Symble_Label_3 = QLabel(self.ScoreBoard)
        self.Clock_Symble_Label_3.setObjectName(u"Clock_Symble_Label_3")
        self.Clock_Symble_Label_3.setGeometry(QRect(357, 262, 10, 29))
        font8 = QFont()
        font8.setFamily(u"Arial")
        font8.setPointSize(18)
        font8.setBold(True)
        font8.setWeight(75)
        self.Clock_Symble_Label_3.setFont(font8)
        self.To_Checkbox = QCheckBox(self.ScoreBoard)
        self.To_Checkbox.setObjectName(u"To_Checkbox")
        self.To_Checkbox.setGeometry(QRect(183, 224, 88, 19))
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.To_Checkbox.sizePolicy().hasHeightForWidth())
        self.To_Checkbox.setSizePolicy(sizePolicy4)
        self.To_Checkbox.setFont(font4)
        self.To_Checkbox.setAutoFillBackground(False)
        self.Clock_Symble_Label_2 = QLabel(self.ScoreBoard)
        self.Clock_Symble_Label_2.setObjectName(u"Clock_Symble_Label_2")
        self.Clock_Symble_Label_2.setGeometry(QRect(357, 215, 10, 29))
        sizePolicy5 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.Clock_Symble_Label_2.sizePolicy().hasHeightForWidth())
        self.Clock_Symble_Label_2.setSizePolicy(sizePolicy5)
        self.Clock_Symble_Label_2.setFont(font8)
        self.Clock_Symble_Label = QLabel(self.ScoreBoard)
        self.Clock_Symble_Label.setObjectName(u"Clock_Symble_Label")
        self.Clock_Symble_Label.setGeometry(QRect(357, 170, 10, 29))
        self.Clock_Symble_Label.setFont(font8)
        self.SecondsTo_Input = QSpinBox(self.ScoreBoard)
        self.SecondsTo_Input.setObjectName(u"SecondsTo_Input")
        self.SecondsTo_Input.setEnabled(False)
        self.SecondsTo_Input.setGeometry(QRect(375, 215, 65, 35))
        sizePolicy.setHeightForWidth(self.SecondsTo_Input.sizePolicy().hasHeightForWidth())
        self.SecondsTo_Input.setSizePolicy(sizePolicy)
        font9 = QFont()
        font9.setPointSize(18)
        font9.setBold(False)
        font9.setItalic(False)
        font9.setWeight(50)
        font9.setKerning(True)
        self.SecondsTo_Input.setFont(font9)
        self.SecondsTo_Input.setAlignment(Qt.AlignCenter)
        self.SecondsTo_Input.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.SecondsTo_Input.setAccelerated(True)
        self.SecondsTo_Input.setProperty("showGroupSeparator", False)
        self.SecondsTo_Input.setMaximum(59)
        self.SecondsPeriod_Input = QSpinBox(self.ScoreBoard)
        self.SecondsPeriod_Input.setObjectName(u"SecondsPeriod_Input")
        self.SecondsPeriod_Input.setGeometry(QRect(375, 262, 65, 35))
        sizePolicy.setHeightForWidth(self.SecondsPeriod_Input.sizePolicy().hasHeightForWidth())
        self.SecondsPeriod_Input.setSizePolicy(sizePolicy)
        self.SecondsPeriod_Input.setFont(font7)
        self.SecondsPeriod_Input.setAlignment(Qt.AlignCenter)
        self.SecondsPeriod_Input.setAccelerated(True)
        self.SecondsPeriod_Input.setMaximum(59)
        self.MinutesTo_Input = QSpinBox(self.ScoreBoard)
        self.MinutesTo_Input.setObjectName(u"MinutesTo_Input")
        self.MinutesTo_Input.setEnabled(False)
        self.MinutesTo_Input.setGeometry(QRect(281, 215, 65, 35))
        sizePolicy6 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.MinutesTo_Input.sizePolicy().hasHeightForWidth())
        self.MinutesTo_Input.setSizePolicy(sizePolicy6)
        self.MinutesTo_Input.setFont(font7)
        self.MinutesTo_Input.setAlignment(Qt.AlignCenter)
        self.MinutesTo_Input.setAccelerated(True)
        self.MinutesTo_Input.setMaximum(999)
        self.TimeSet_Label = QLabel(self.ScoreBoard)
        self.TimeSet_Label.setObjectName(u"TimeSet_Label")
        self.TimeSet_Label.setGeometry(QRect(189, 179, 71, 20))
        self.TimeSet_Label.setFont(font4)
        self.TimeSet_Label.setAlignment(Qt.AlignCenter)
        self.PeriodUP_Button = QPushButton(self.ScoreBoard)
        self.PeriodUP_Button.setObjectName(u"PeriodUP_Button")
        self.PeriodUP_Button.setGeometry(QRect(479, 299, 61, 31))
        self.PeriodDOWN_Button = QPushButton(self.ScoreBoard)
        self.PeriodDOWN_Button.setObjectName(u"PeriodDOWN_Button")
        self.PeriodDOWN_Button.setGeometry(QRect(619, 299, 61, 31))
        self.StopSound_Button = QPushButton(self.ScoreBoard)
        self.StopSound_Button.setObjectName(u"StopSound_Button")
        self.StopSound_Button.setGeometry(QRect(280, 390, 121, 23))
        self.PeriodTxt_Label = QLabel(self.ScoreBoard)
        self.PeriodTxt_Label.setObjectName(u"PeriodTxt_Label")
        self.PeriodTxt_Label.setGeometry(QRect(550, 250, 70, 27))
        font10 = QFont()
        font10.setFamily(u"Arial")
        font10.setPointSize(16)
        self.PeriodTxt_Label.setFont(font10)
        self.Period_Label = QLabel(self.ScoreBoard)
        self.Period_Label.setObjectName(u"Period_Label")
        self.Period_Label.setGeometry(QRect(546, 279, 71, 71))
        font11 = QFont()
        font11.setFamily(u"Arial")
        font11.setPointSize(48)
        font11.setBold(False)
        font11.setItalic(False)
        font11.setUnderline(False)
        font11.setWeight(50)
        font11.setStrikeOut(False)
        font11.setKerning(True)
        self.Period_Label.setFont(font11)
        self.Period_Label.setAlignment(Qt.AlignCenter)
        self.HalfTime_Button = QPushButton(self.ScoreBoard)
        self.HalfTime_Button.setObjectName(u"HalfTime_Button")
        self.HalfTime_Button.setGeometry(QRect(430, 430, 90, 50))
        self.HalfTime_Button.setFont(font)
        self.ResetTimer_Button = QPushButton(self.ScoreBoard)
        self.ResetTimer_Button.setObjectName(u"ResetTimer_Button")
        self.ResetTimer_Button.setGeometry(QRect(150, 430, 101, 51))
        self.ResetTimer_Button.setFont(font)
        self.Start_Button = QPushButton(self.ScoreBoard)
        self.Start_Button.setObjectName(u"Start_Button")
        self.Start_Button.setGeometry(QRect(280, 420, 121, 71))
        font12 = QFont()
        font12.setFamily(u"Microsoft JhengHei UI")
        font12.setPointSize(20)
        font12.setBold(False)
        font12.setWeight(50)
        self.Start_Button.setFont(font12)
        self.Start_Button.setStyleSheet(u"")
        self.Swap_Button = QPushButton(self.ScoreBoard)
        self.Swap_Button.setObjectName(u"Swap_Button")
        self.Swap_Button.setGeometry(QRect(650, 430, 90, 51))
        self.Swap_Button.setFont(font)
        self.UpdateTeam_Button = QPushButton(self.ScoreBoard)
        self.UpdateTeam_Button.setObjectName(u"UpdateTeam_Button")
        self.UpdateTeam_Button.setGeometry(QRect(10, 430, 121, 50))
        self.UpdateTeam_Button.setFont(font)
        self.UpdateTeam_Button.setStyleSheet(u"alternate-background-color: rgb(85, 170, 127);")
        self.ResetScore_Button = QPushButton(self.ScoreBoard)
        self.ResetScore_Button.setObjectName(u"ResetScore_Button")
        self.ResetScore_Button.setGeometry(QRect(540, 430, 90, 51))
        self.ResetScore_Button.setFont(font)
        self.ResetScore_Button.setStyleSheet(u"")
        self.HalfTimeClock_Label = QLabel(self.ScoreBoard)
        self.HalfTimeClock_Label.setObjectName(u"HalfTimeClock_Label")
        self.HalfTimeClock_Label.setGeometry(QRect(440, 390, 68, 32))
        self.HalfTimeClock_Label.setFont(font6)
        self.HalfTime_Label = QLabel(self.ScoreBoard)
        self.HalfTime_Label.setObjectName(u"HalfTime_Label")
        self.HalfTime_Label.setGeometry(QRect(430, 352, 91, 41))
        self.HalfTime_Label.setFont(font4)
        self.HalfTime_Label.setAlignment(Qt.AlignCenter)
        self.Error_Text = QLabel(self.ScoreBoard)
        self.Error_Text.setObjectName(u"Error_Text")
        self.Error_Text.setEnabled(True)
        self.Error_Text.setGeometry(QRect(20, 290, 241, 111))
        font13 = QFont()
        font13.setPointSize(8)
        font13.setBold(False)
        font13.setWeight(50)
        self.Error_Text.setFont(font13)
        self.Error_Text.setAutoFillBackground(False)
        self.Error_Text.setTextFormat(Qt.AutoText)
        self.Error_Text.setScaledContents(False)
        self.Error_Text.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.Error_Text.setWordWrap(True)
        self.Error_Text.setMargin(0)
        self.Error_Text.setIndent(0)
        self.tabWidget.addTab(self.ScoreBoard, "")
        self.Settings = QWidget()
        self.Settings.setObjectName(u"Settings")
        self.groupBox = QGroupBox(self.Settings)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 10, 151, 130))
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.StopWatch_Radio = QRadioButton(self.groupBox)
        self.StopWatch_Radio.setObjectName(u"StopWatch_Radio")
        self.StopWatch_Radio.setGeometry(QRect(11, 30, 91, 17))
        self.StopWatch_Radio.setFont(font)
        self.StopWatch_Radio.setChecked(True)
        self.Timer_Radio = QRadioButton(self.groupBox)
        self.Timer_Radio.setObjectName(u"Timer_Radio")
        self.Timer_Radio.setGeometry(QRect(11, 59, 91, 17))
        self.Timer_Radio.setFont(font)
        self.CurrentTime_Radio = QRadioButton(self.groupBox)
        self.CurrentTime_Radio.setObjectName(u"CurrentTime_Radio")
        self.CurrentTime_Radio.setGeometry(QRect(11, 88, 111, 17))
        font14 = QFont()
        font14.setPointSize(9)
        self.CurrentTime_Radio.setFont(font14)
        self.Countdown_Checkbox = QCheckBox(self.Settings)
        self.Countdown_Checkbox.setObjectName(u"Countdown_Checkbox")
        self.Countdown_Checkbox.setGeometry(QRect(210, 20, 141, 31))
        self.Countdown_Checkbox.setFont(font)
        self.line_2 = QFrame(self.Settings)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(181, 63, 582, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.Settings)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(380, 0, 3, 140))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.Always_on_top_Checkbox = QCheckBox(self.Settings)
        self.Always_on_top_Checkbox.setObjectName(u"Always_on_top_Checkbox")
        self.Always_on_top_Checkbox.setGeometry(QRect(410, 20, 141, 31))
        self.Always_on_top_Checkbox.setFont(font)
        self.line_4 = QFrame(self.Settings)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(580, 0, 3, 70))
        font15 = QFont()
        font15.setPointSize(12)
        self.line_4.setFont(font15)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.Milliseconds_Checkbox = QCheckBox(self.Settings)
        self.Milliseconds_Checkbox.setObjectName(u"Milliseconds_Checkbox")
        self.Milliseconds_Checkbox.setGeometry(QRect(590, 20, 161, 31))
        self.Milliseconds_Checkbox.setFont(font)
        self.line_6 = QFrame(self.Settings)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(180, 132, 582, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.Speed_CheckBox = QCheckBox(self.Settings)
        self.Speed_CheckBox.setObjectName(u"Speed_CheckBox")
        self.Speed_CheckBox.setGeometry(QRect(403, 90, 91, 31))
        self.Speed_CheckBox.setFont(font)
        self.SpeedHelp_Button = QPushButton(self.Settings)
        self.SpeedHelp_Button.setObjectName(u"SpeedHelp_Button")
        self.SpeedHelp_Button.setGeometry(QRect(620, 90, 75, 31))
        self.SpeedHelp_Button.setFont(font)
        self.Speed_Input = QSpinBox(self.Settings)
        self.Speed_Input.setObjectName(u"Speed_Input")
        self.Speed_Input.setGeometry(QRect(500, 90, 61, 31))
        self.Speed_Input.setFont(font)
        self.Speed_Input.setAlignment(Qt.AlignCenter)
        self.Speed_Input.setAccelerated(True)
        self.Speed_Input.setMinimum(500)
        self.Speed_Input.setMaximum(3000)
        self.Speed_Input.setSingleStep(1)
        self.Speed_Input.setValue(700)
        self.groupBox_2 = QGroupBox(self.Settings)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(30, 170, 701, 130))
        self.groupBox_2.setFont(font)
        self.TimerPreset_Checkbox = QCheckBox(self.groupBox_2)
        self.TimerPreset_Checkbox.setObjectName(u"TimerPreset_Checkbox")
        self.TimerPreset_Checkbox.setGeometry(QRect(40, 26, 141, 31))
        self.TimerPreset_Checkbox.setFont(font)
        self.FiveP_Radio = QRadioButton(self.groupBox_2)
        self.FiveP_Radio.setObjectName(u"FiveP_Radio")
        self.FiveP_Radio.setEnabled(False)
        self.FiveP_Radio.setGeometry(QRect(100, 70, 82, 17))
        self.FiveP_Radio.setFont(font)
        self.FiveP_Radio.setChecked(True)
        self.TwentyP_Radio = QRadioButton(self.groupBox_2)
        self.TwentyP_Radio.setObjectName(u"TwentyP_Radio")
        self.TwentyP_Radio.setEnabled(False)
        self.TwentyP_Radio.setGeometry(QRect(370, 70, 82, 17))
        self.TwentyP_Radio.setFont(font)
        self.TenP_Radio = QRadioButton(self.groupBox_2)
        self.TenP_Radio.setObjectName(u"TenP_Radio")
        self.TenP_Radio.setEnabled(False)
        self.TenP_Radio.setGeometry(QRect(190, 70, 82, 17))
        self.TenP_Radio.setFont(font)
        self.TwentyP_Radio_2 = QRadioButton(self.groupBox_2)
        self.TwentyP_Radio_2.setObjectName(u"TwentyP_Radio_2")
        self.TwentyP_Radio_2.setEnabled(False)
        self.TwentyP_Radio_2.setGeometry(QRect(460, 70, 82, 17))
        self.TwentyP_Radio_2.setFont(font)
        self.FifteenP_Radio = QRadioButton(self.groupBox_2)
        self.FifteenP_Radio.setObjectName(u"FifteenP_Radio")
        self.FifteenP_Radio.setEnabled(False)
        self.FifteenP_Radio.setGeometry(QRect(280, 70, 82, 17))
        self.FifteenP_Radio.setFont(font)
        self.TwentyP_Radio_3 = QRadioButton(self.groupBox_2)
        self.TwentyP_Radio_3.setObjectName(u"TwentyP_Radio_3")
        self.TwentyP_Radio_3.setEnabled(False)
        self.TwentyP_Radio_3.setGeometry(QRect(550, 70, 82, 17))
        self.TwentyP_Radio_3.setFont(font)
        self.line_5 = QFrame(self.Settings)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 340, 752, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.Use_Xml_CheckBox = QCheckBox(self.Settings)
        self.Use_Xml_CheckBox.setObjectName(u"Use_Xml_CheckBox")
        self.Use_Xml_CheckBox.setGeometry(QRect(60, 370, 141, 31))
        self.Use_Xml_CheckBox.setFont(font)
        self.tabWidget.addTab(self.Settings, "")
        self.line_6.raise_()
        self.groupBox.raise_()
        self.Countdown_Checkbox.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.Always_on_top_Checkbox.raise_()
        self.line_4.raise_()
        self.Milliseconds_Checkbox.raise_()
        self.Speed_CheckBox.raise_()
        self.SpeedHelp_Button.raise_()
        self.Speed_Input.raise_()
        self.groupBox_2.raise_()
        self.line_5.raise_()
        self.Use_Xml_CheckBox.raise_()
        self.Hotkeys = QWidget()
        self.Hotkeys.setObjectName(u"Hotkeys")
        self.Hotkey_Checkbox = QCheckBox(self.Hotkeys)
        self.Hotkey_Checkbox.setObjectName(u"Hotkey_Checkbox")
        self.Hotkey_Checkbox.setGeometry(QRect(30, 10, 411, 41))
        self.Hotkey_Checkbox.setFont(font1)
        self.line = QFrame(self.Hotkeys)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 50, 751, 21))
        sizePolicy4.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy4)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(self.Hotkeys)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 91, 70, 20))
        self.label.setFont(font)
        self.lineEdit = QLineEdit(self.Hotkeys)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QRect(80, 91, 130, 20))
        self.label_2 = QLabel(self.Hotkeys)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 150, 70, 20))
        self.label_2.setFont(font)
        self.lineEdit_2 = QLineEdit(self.Hotkeys)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QRect(80, 150, 130, 20))
        self.lineEdit_3 = QLineEdit(self.Hotkeys)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QRect(80, 270, 130, 20))
        self.label_3 = QLabel(self.Hotkeys)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 210, 70, 20))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.Hotkeys)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 270, 70, 20))
        self.label_4.setFont(font)
        self.lineEdit_4 = QLineEdit(self.Hotkeys)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QRect(80, 210, 130, 20))
        self.lineEdit_5 = QLineEdit(self.Hotkeys)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QRect(80, 390, 130, 20))
        self.label_5 = QLabel(self.Hotkeys)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 330, 70, 20))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.Hotkeys)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 390, 70, 20))
        self.label_6.setFont(font)
        self.lineEdit_6 = QLineEdit(self.Hotkeys)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QRect(80, 330, 130, 20))
        self.lineEdit_7 = QLineEdit(self.Hotkeys)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QRect(620, 149, 130, 20))
        self.label_7 = QLabel(self.Hotkeys)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(519, 90, 91, 20))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.Hotkeys)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(519, 149, 91, 20))
        self.label_8.setFont(font)
        self.lineEdit_8 = QLineEdit(self.Hotkeys)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QRect(620, 90, 130, 20))
        self.lineEdit_9 = QLineEdit(self.Hotkeys)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QRect(350, 330, 130, 20))
        self.label_9 = QLabel(self.Hotkeys)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(519, 210, 101, 20))
        self.label_9.setFont(font)
        self.label_10 = QLabel(self.Hotkeys)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(249, 330, 91, 20))
        self.label_10.setFont(font)
        self.lineEdit_10 = QLineEdit(self.Hotkeys)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setGeometry(QRect(620, 210, 130, 20))
        self.lineEdit_11 = QLineEdit(self.Hotkeys)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QRect(350, 149, 130, 20))
        self.label_11 = QLabel(self.Hotkeys)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(249, 90, 91, 20))
        self.label_11.setFont(font)
        self.label_12 = QLabel(self.Hotkeys)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(249, 149, 91, 20))
        self.label_12.setFont(font)
        self.lineEdit_12 = QLineEdit(self.Hotkeys)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setGeometry(QRect(350, 90, 130, 20))
        self.lineEdit_13 = QLineEdit(self.Hotkeys)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setGeometry(QRect(350, 269, 130, 20))
        self.label_13 = QLabel(self.Hotkeys)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(249, 210, 91, 20))
        self.label_13.setFont(font)
        self.label_14 = QLabel(self.Hotkeys)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(249, 269, 91, 20))
        self.label_14.setFont(font)
        self.lineEdit_14 = QLineEdit(self.Hotkeys)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setEnabled(False)
        self.lineEdit_14.setGeometry(QRect(350, 210, 130, 20))
        self.line_7 = QFrame(self.Hotkeys)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(230, 60, 20, 351))
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(self.Hotkeys)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(500, 60, 20, 351))
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.Hotkeys, "")
        self.Sound = QWidget()
        self.Sound.setObjectName(u"Sound")
        self.PlaySound_Checkbox = QCheckBox(self.Sound)
        self.PlaySound_Checkbox.setObjectName(u"PlaySound_Checkbox")
        self.PlaySound_Checkbox.setEnabled(True)
        self.PlaySound_Checkbox.setGeometry(QRect(40, 40, 121, 41))
        self.PlaySound_Checkbox.setFont(font1)
        self.BrowseFile_Input = QLineEdit(self.Sound)
        self.BrowseFile_Input.setObjectName(u"BrowseFile_Input")
        self.BrowseFile_Input.setEnabled(False)
        self.BrowseFile_Input.setGeometry(QRect(20, 99, 221, 25))
        self.TestSound_Button = QPushButton(self.Sound)
        self.TestSound_Button.setObjectName(u"TestSound_Button")
        self.TestSound_Button.setEnabled(False)
        self.TestSound_Button.setGeometry(QRect(350, 99, 75, 25))
        self.BrowseFile_Button = QPushButton(self.Sound)
        self.BrowseFile_Button.setObjectName(u"BrowseFile_Button")
        self.BrowseFile_Button.setEnabled(False)
        self.BrowseFile_Button.setGeometry(QRect(250, 100, 91, 25))
        self.Volume_Slider = QSlider(self.Sound)
        self.Volume_Slider.setObjectName(u"Volume_Slider")
        self.Volume_Slider.setEnabled(False)
        self.Volume_Slider.setGeometry(QRect(90, 180, 561, 31))
        self.Volume_Slider.setOrientation(Qt.Horizontal)
        self.SoundSpeed_Slider = QSlider(self.Sound)
        self.SoundSpeed_Slider.setObjectName(u"SoundSpeed_Slider")
        self.SoundSpeed_Slider.setEnabled(False)
        self.SoundSpeed_Slider.setGeometry(QRect(90, 230, 561, 31))
        self.SoundSpeed_Slider.setMinimum(-10)
        self.SoundSpeed_Slider.setMaximum(10)
        self.SoundSpeed_Slider.setOrientation(Qt.Horizontal)
        self.Warning_Label = QLabel(self.Sound)
        self.Warning_Label.setObjectName(u"Warning_Label")
        self.Warning_Label.setEnabled(True)
        self.Warning_Label.setGeometry(QRect(90, 280, 561, 71))
        font16 = QFont()
        font16.setFamily(u"Arial")
        font16.setPointSize(36)
        self.Warning_Label.setFont(font16)
        self.Warning_Label.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.tabWidget.addTab(self.Sound, "")
        self.Remote = QWidget()
        self.Remote.setObjectName(u"Remote")
        self.Remote_Button = QPushButton(self.Remote)
        self.Remote_Button.setObjectName(u"Remote_Button")
        self.Remote_Button.setGeometry(QRect(90, 40, 181, 31))
        self.Remote_Button.setFont(font)
        self.IP_Label = QLabel(self.Remote)
        self.IP_Label.setObjectName(u"IP_Label")
        self.IP_Label.setGeometry(QRect(80, 215, 561, 31))
        self.IP_Label.setFont(font2)
        self.Status_Label = QLabel(self.Remote)
        self.Status_Label.setObjectName(u"Status_Label")
        self.Status_Label.setGeometry(QRect(70, 280, 581, 71))
        self.Status_Label.setFont(font7)
        self.Status_Label.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.IP_Label_2 = QLabel(self.Remote)
        self.IP_Label_2.setObjectName(u"IP_Label_2")
        self.IP_Label_2.setGeometry(QRect(80, 250, 561, 21))
        self.IP_Label_2.setFont(font15)
        self.tabWidget.addTab(self.Remote, "")
        self.Obs = QWidget()
        self.Obs.setObjectName(u"Obs")
        self.label_15 = QLabel(self.Obs)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 40, 91, 31))
        self.label_15.setFont(font1)
        self.label_16 = QLabel(self.Obs)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 80, 91, 31))
        self.label_16.setFont(font1)
        self.lineEdit_15 = QLineEdit(self.Obs)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(120, 40, 113, 31))
        self.lineEdit_15.setFont(font)
        self.lineEdit_16 = QLineEdit(self.Obs)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(120, 80, 113, 31))
        self.lineEdit_16.setFont(font)
        self.label_17 = QLabel(self.Obs)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(250, 80, 111, 31))
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QFrame.StyledPanel)
        self.label_17.setFrameShadow(QFrame.Sunken)
        self.label_18 = QLabel(self.Obs)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(250, 40, 131, 31))
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QFrame.StyledPanel)
        self.label_18.setFrameShadow(QFrame.Sunken)
        self.Remote_Button_2 = QPushButton(self.Obs)
        self.Remote_Button_2.setObjectName(u"Remote_Button_2")
        self.Remote_Button_2.setGeometry(QRect(130, 140, 181, 31))
        self.Remote_Button_2.setFont(font)
        self.label_19 = QLabel(self.Obs)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(410, 35, 161, 31))
        self.label_19.setFont(font1)
        self.label_20 = QLabel(self.Obs)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(410, 75, 161, 31))
        self.label_20.setFont(font1)
        self.comboBox = QComboBox(self.Obs)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(570, 40, 117, 24))
        self.comboBox.setFont(font1)
        self.comboBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.comboBox.setMinimumContentsLength(10)
        self.comboBox.setFrame(True)
        self.comboBox_2 = QComboBox(self.Obs)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(570, 80, 90, 24))
        self.comboBox_2.setFont(font1)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.comboBox_2.setMinimumContentsLength(7)
        self.tabWidget.addTab(self.Obs, "")

        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menuLanguage = QMenu(self.menubar)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuContributers = QMenu(self.menubar)
        self.menuContributers.setObjectName(u"menuContributers")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuDonate = QMenu(self.menubar)
        self.menuDonate.setObjectName(u"menuDonate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuContributers.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDonate.menuAction())
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionPolski)
        self.menuContributers.addAction(self.actionha0511kr)
        self.menuContributers.addAction(self.actionXxRocketshotxX)
        self.menuContributers.addAction(self.actionSickmind33)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionChangelog)
        self.menuHelp.addAction(self.actionHelp)
        self.menuDonate.addAction(self.actionDonate)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        self.comboBox_2.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionPolski.setText(QCoreApplication.translate("MainWindow", u"Polski", None))
        self.actionha0511kr.setText(QCoreApplication.translate("MainWindow", u"ha0511kr", None))
        self.actionXxRocketshotxX.setText(QCoreApplication.translate("MainWindow", u"XxRocketshotxX", None))
        self.actionSickmind33.setText(QCoreApplication.translate("MainWindow", u"Sickmind33", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionChangelog.setText(QCoreApplication.translate("MainWindow", u"Changelog", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.actionDonate.setText(QCoreApplication.translate("MainWindow", u"Donate", None))
        self.AwayUp2_Button.setText(QCoreApplication.translate("MainWindow", u"+2", None))
        self.AwayName_Input.setText(QCoreApplication.translate("MainWindow", u"Away", None))
        self.AwayDOWN_Button.setText(QCoreApplication.translate("MainWindow", u"DOWN", None))
        self.AwayScore_Label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.AwayUP_Button.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.HomeUP2_Button.setText(QCoreApplication.translate("MainWindow", u"+2", None))
        self.HomeDOWN_Button.setText(QCoreApplication.translate("MainWindow", u"DOWN", None))
        self.HomeName_Input.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.HomeUP_Button.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.HomeScore_Label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.PeriodTime_Label.setText(QCoreApplication.translate("MainWindow", u"Period Time", None))
        self.Clock_Label.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.ExtraClock_Label.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.ExtraTime_Label.setText(QCoreApplication.translate("MainWindow", u"Extra Time", None))
        self.PeriodClock_Label.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.PeriodLength_Label.setText(QCoreApplication.translate("MainWindow", u"Period Length", None))
        self.Clock_Symble_Label_3.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.To_Checkbox.setText(QCoreApplication.translate("MainWindow", u"To(optional)", None))
        self.Clock_Symble_Label_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.Clock_Symble_Label.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.TimeSet_Label.setText(QCoreApplication.translate("MainWindow", u"Time Set", None))
        self.PeriodUP_Button.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.PeriodDOWN_Button.setText(QCoreApplication.translate("MainWindow", u"DOWN", None))
        self.StopSound_Button.setText(QCoreApplication.translate("MainWindow", u"Stop Sound", None))
        self.PeriodTxt_Label.setText(QCoreApplication.translate("MainWindow", u"Period:", None))
        self.Period_Label.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.HalfTime_Button.setText(QCoreApplication.translate("MainWindow", u"Half Time", None))
        self.ResetTimer_Button.setText(QCoreApplication.translate("MainWindow", u"Reset Timer", None))
        self.Start_Button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Swap_Button.setText(QCoreApplication.translate("MainWindow", u"Swap", None))
        self.UpdateTeam_Button.setText(QCoreApplication.translate("MainWindow", u"Update Team", None))
        self.ResetScore_Button.setText(QCoreApplication.translate("MainWindow", u"Reset Score", None))
        self.HalfTimeClock_Label.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.HalfTime_Label.setText(QCoreApplication.translate("MainWindow", u" Half Time\n"
"Break Time", None))
        self.Error_Text.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Error Output:</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ScoreBoard), QCoreApplication.translate("MainWindow", u"Scoreboard", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Timer Settings", None))
        self.StopWatch_Radio.setText(QCoreApplication.translate("MainWindow", u"StopWatch", None))
        self.Timer_Radio.setText(QCoreApplication.translate("MainWindow", u"Timer", None))
        self.CurrentTime_Radio.setText(QCoreApplication.translate("MainWindow", u"Current Time", None))
        self.Countdown_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Time in Input Box", None))
        self.Always_on_top_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Always on top", None))
        self.Milliseconds_Checkbox.setText(QCoreApplication.translate("MainWindow", u"1/10 Second min < 1", None))
        self.Speed_CheckBox.setText(QCoreApplication.translate("MainWindow", u"Speed:", None))
        self.SpeedHelp_Button.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Timer Presets", None))
        self.TimerPreset_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Preset Timer Reset", None))
        self.FiveP_Radio.setText(QCoreApplication.translate("MainWindow", u"10:00", None))
        self.TwentyP_Radio.setText(QCoreApplication.translate("MainWindow", u"20:00", None))
        self.TenP_Radio.setText(QCoreApplication.translate("MainWindow", u"12:00", None))
        self.TwentyP_Radio_2.setText(QCoreApplication.translate("MainWindow", u"30:00", None))
        self.FifteenP_Radio.setText(QCoreApplication.translate("MainWindow", u"15:00", None))
        self.TwentyP_Radio_3.setText(QCoreApplication.translate("MainWindow", u"45:00", None))
        self.Use_Xml_CheckBox.setText(QCoreApplication.translate("MainWindow", u"Use XML Flie", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.Hotkey_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Use Hotkey", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Home UP", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Home DWN", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Home +2", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Away UP", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Away DWN", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Away +2", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Period UP", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Period DWN", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Stop Sound", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Swap Teams", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Start/Stop", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Reset Timer", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Half Time", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Reset Score", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Hotkeys), QCoreApplication.translate("MainWindow", u"HotKeys", None))
        self.PlaySound_Checkbox.setText(QCoreApplication.translate("MainWindow", u"Play Sound", None))
        self.TestSound_Button.setText(QCoreApplication.translate("MainWindow", u"Test Sound", None))
        self.BrowseFile_Button.setText(QCoreApplication.translate("MainWindow", u"Browse File", None))
        self.Warning_Label.setText(QCoreApplication.translate("MainWindow", u"Please stop the sound", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sound), QCoreApplication.translate("MainWindow", u"Sound", None))
        self.Remote_Button.setText(QCoreApplication.translate("MainWindow", u"Start Server", None))
        self.IP_Label.setText(QCoreApplication.translate("MainWindow", u"Default IP: 127.0.0.1/Localhost | Port: 1234", None))
        self.Status_Label.setText(QCoreApplication.translate("MainWindow", u"Status: Not Connected", None))
        self.IP_Label_2.setText(QCoreApplication.translate("MainWindow", u"If you want to remote over internet please portfoward or use VPS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Remote), QCoreApplication.translate("MainWindow", u"Remote", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Host / IP", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"default: 4444", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"default: localhost", None))
        self.Remote_Button_2.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"In Game Scene", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Half Time Scene", None))
        self.comboBox_2.setCurrentText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Obs), QCoreApplication.translate("MainWindow", u"OBS", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
        self.menuContributers.setTitle(QCoreApplication.translate("MainWindow", u"Contributers", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuDonate.setTitle(QCoreApplication.translate("MainWindow", u"Donate", None))
    # retranslateUi

